// Fitxer: dades.js
// 1. DICCIONARI COMPLET D'UNITATS (Extret del fitxer)
const diccionariUnitats_basic = {
  //Present
  1: "am/is/are",
  2: "am/is/are (questions)",
  3: "I am doing (present continuous)",
  4: "are you doing? (present continuous questions)",
  5: "I do/work/like, etc. (simple present)",
  6: "I don't (simple present negative)",
  7: "Do you ... ? (simple present questions)",
  8: "I am doing and I do (present continuous vs. simple present)",
  9: "I have ... and I've got",

  //Past
  10: "was/were",
  11: "worked/got/went, etc. (simple past)",
  12: "I didn't ... Did you ... ? (past negative and questions)",
  13: "I was doing (past continuous)",
  14: "I was doing and I did (past continuous vs. simple past)",
  15: "I used to",

  //Present Perfect
  16: "Have you ... ?",
  17: "How long have you ... ?",
  18: "for / since / ago",
  19: "I have done and I did (present perfect vs. past)",

  //Passive
  20: "is done / was done (passive 1)",
  21: "is being done / has been done (passive 2)",

  //Verbs Forms
  22: "be/have/do in present and past tenses",
  23: "Regular and irregular verbs",

  //Future
  24: "What are you doing tomorrow?",
  25: "I'm going to",
  26: "will",
  27: "might",

  //Modals, imperative, etc.
  28: "can and could",
  29: "must",
  30: "should",
  31: "I have to ...",
  32: "Would you like...? I'd like...",
  33: "I'd rather",
  34: "Do this! Don't do that! Let's do this!",

  //There and it
  35: "there is / there are",
  36: "there was/were / there has/have been / there will be",
  37: "it",

  //Auxiliary verbs
  38: "I am, I don't, etc.",
  39: "You have? Have you? You are? Are you?, etc.",
  40: "too/either / so am I / neither do I, etc.",
  41: "isn't, haven't, don't, etc. (negatives)",

  //Questions
  42: "is it? have you? do they?, etc. (questions 1)",
  43: "Who saw you? Who did you see? (questions 2)",
  44: "Who is she talking to? What is it like? (questions 3)",
  45: "What ... ? Which ... ? How ... ? (questions 4)",
  46: "How long does it take ... ?",
  47: "Do you know where ... ? I don't know what ...",

  //Reported speech
  48: "She said that ... He told me that (reported speech)",
  49: "work/working / go/going / do/doing",

  //-ing and to .
  50: "to ... (I want to do) and -ing (I enjoy doing)",
  51: "I want you to ... / I told you to ...",
  52: "I went to the store to ...",

  //get, do, make, and have
  53: "go to / go on / go for / go -ing",
  54: "get",
  55: "do and make",
  56: "have",

  //Pronouns and possessives
  57: "I/me / he/him / they/them, etc.",
  58: "my/his/their, etc.",
  59: "Whose is this? It's mine/yours/hers, etc.",
  60: "I/my/mine",
  61: "myself/yourself/themselves, etc.",
  62: "-'s (Kate's camera / my brother's car, etc.)",

  //A and the
  63: "a/an ...",
  64: "train(s) / bus(es) (singular and plural)",
  65: "a bottle / some water (count/noncount 1)",
  66: "a cake / some cake / some cakes (count/noncount 2)",
  67: "a/an and the",
  68: "the ...",
  69: "go to work / go home / go to the hospital",
  70: "I like music / I hate exams",
  71: "the ... (names of places)",

  //Determiners and pronouns
  72: "this/that/these/those",
  73: "one/ones",
  74: "some and any",
  75: "not + any / no / none",
  76: "not + anybody/anyone/anything",
  77: "somebody / anything / nowhere, etc.",
  78: "every and all",
  79: "all / most / some / any / no / none",
  80: "both / either / neither",
  81: "a lot / much / many",
  82: "(a) little / (a) few / nobody / no one / nothing",

  //Adjectives and adverbs
  83: "old/nice/interesting, etc. (adjectives)",
  84: "quickly/badly/suddenly, etc. (adverbs)",
  85: "old/older / expensive / more expensive",
  86: "older than ... / more expensive than ...",
  87: "not as ... as",
  88: "the oldest / the most expensive",
  89: "enough",
  90: "too",

  //Word order
  91: "He speaks English very well. (word order 1)",
  92: "always/usually/often, etc. (word order 2)",
  93: "still / yet / already",
  94: "Give me that book! / Give it to me!",

  //Conjunctions and clauses
  95: "and / but / or / so / because",
  96: "When ...",
  97: "If we go ... / If you see ..., etc.",
  98: "If I had ... / If we went ..., etc.",
  99: "a person who ... / a thing that/which ... (relative clauses 1)",
  100: "the people we met / the hotel you stayed at (relative clauses 2)",

  //Prepositions
  101: "at 8:00 / on Monday / in April",
  102: "from ... to / until / since / for",
  103: "before / after / during / while",
  104: "in / at / on (places 1)",
  105: "in / at / on (places 2)",
  106: "to / in / at (places 3)",
  107: "next to / between / under, etc.",
  108: "up / over / through, etc.",
  109: "on / at / by / with / about",
  110: "afraid of ..., good at ..., etc. / of/at/for + -ing",
  111: "listen to / look at ..., etc. (verb + preposition)",

  //Phrasal verbs
  112: "go in / fall off / run away, etc. (phrasal verbs 1)",
  113: "put on your shoes / put your shoes on (phrasal verbs 2)",
};

// 2. ESTRUCTURA DE LES ACTIVITATS (Basat en Cambridge Basic)
const dades_basic = {
  issues: [
    {
      titol: "Present",
      preguntes: [
        {
          id: "1.1",
          text_pre: "",
          text_post: ". Can I close the window?",
          opcions: ["A I cold", "B I'm cold", "C I have cold", "D It has cold"],
          solucions: ["B"],
          unitats: [1],
        },
        {
          id: "1.2",
          text_pre: "Tom",
          text_post: ". He's at work.",
          opcions: [
            "A isn't here",
            "B not here",
            "C doesn't here",
            "D no is here",
          ],
          solucions: ["A"],
          unitats: [1],
        },
        {
          id: "1.3",
          text_pre: '"',
          text_post: '?" "No, she\'s out."',
          opcions: [
            "A Is home your mother",
            "C Is your mother home",
            "D Are your mother home",
          ],
          solucions: ["C"],
          unitats: [2],
        },
        {
          id: "1.4",
          text_pre: "These shoes are nice.",
          text_post: "",
          opcions: [
            "A How much are they?",
            "B How many are they?",
            "C How much they are?",
            "D How much is they?",
          ],
          solucions: ["A"],
          unitats: [2],
        },
        {
          id: "1.5",
          text_pre: "Look, there's Sarah.",
          text_post: " a brown coat.",
          opcions: [
            "A She wearing",
            "B She has wearing",
            "C She is wearing",
            "D She's wearing",
          ],
          solucions: ["C", "D"],
          unitats: [3, 23],
        },
        {
          id: "1.6",
          text_pre: "You can turn off the TV.",
          text_post: " it.",
          opcions: [
            "A I'm not watch",
            "B I'm not watching",
            "C I not watching",
            "D I don't watching",
          ],
          solucions: ["B"],
          unitats: [3, 23],
        },
        {
          id: "1.7",
          text_pre: '"',
          text_post: ' today?" "Yes, he is."',
          opcions: [
            "A Is working Ben",
            "B Is work Ben",
            "C Is Ben work",
            "D Is Ben working",
          ],
          solucions: ["D"],
          unitats: [4, 22],
        },
        {
          id: "1.8",
          text_pre: "Look, there's Emily!",
          text_post: "",
          opcions: [
            "A Where she is going?",
            "B Where she go?",
            "C Where's she going?",
            "D Where she going?",
          ],
          solucions: ["C"],
          unitats: [4, 22],
        },
        {
          id: "1.9",
          text_pre: "The earth",
          text_post: " around the sun.",
          opcions: ["A going", "B go", "C goes", "D does go", "E is go"],
          solucions: ["C"],
          unitats: [5, 22],
        },
        {
          id: "1.10",
          text_pre: "We",
          text_post: " late on weekends.",
          opcions: [
            "A often sleep",
            "B sleep often",
            "C often sleeping",
            "D are often sleep",
          ],
          solucions: ["A"],
          unitats: [5, 22, 92],
        },
        {
          id: "1.11",
          text_pre: "We",
          text_post: " TV very often.",
          opcions: ["B doesn't watch", "C don't watch", "D don't watching"],
          solucions: ["C"],
          unitats: [6, 22],
        },
        {
          id: "1.12",
          text_pre: "",
          text_post: ' the guitar?" "Yes, but I\'m not very good."',
          opcions: [
            "A Do you play",
            "B Are you play",
            "C Does you play",
            "D Do you playing",
            "E Play you",
          ],
          solucions: ["A"],
          unitats: [7, 22],
        },
        {
          id: "1.13",
          text_pre: "I don't understand this sentence. What",
          text_post: "?",
          opcions: [
            "A mean this word",
            "B means this word",
            "C does mean this word",
            "D does this word mean",
            "E this word means",
          ],
          solucions: ["D"],
          unitats: [7, 22],
        },
        {
          id: "1.14",
          text_pre: "Please be quiet.",
          text_post: "",
          opcions: [
            "A I working.",
            "B I work.",
            "C I'm working.",
            "D I'm work.",
          ],
          solucions: ["C"],
          unitats: [8],
        },
        {
          id: "1.15",
          text_pre: "Tom",
          text_post: " a shower every morning.",
          opcions: ["A takes", "B taking", "C is taking", "D take"],
          solucions: ["A"],
          unitats: [8],
        },
        {
          id: "1.16",
          text_pre: "What",
          text_post: " on weekends?",
          opcions: [
            "A do you usually",
            "B are you usually doing",
            "C are you usually do",
            "D do you usually do",
            "E you do usually",
          ],
          solucions: ["D"],
          unitats: [7, 8, 22],
        },
        {
          id: "1.17",
          text_pre: "Sarah isn't feeling well.",
          text_post: " a headache.",
          opcions: ["A She have", "B She have got", "C She has", "D She's got"],
          solucions: ["C", "D"],
          unitats: [9, 56],
        },
        {
          id: "1.18",
          text_pre: "They",
          text_post: " any children.",
          opcions: [
            "A don't have",
            "B doesn't have",
            "C no have",
            "D haven't got",
            "E hasn't got",
          ],
          solucions: ["A", "D"],
          unitats: [9, 56],
        },
      ],
    },
    {
      titol: "Past",
      preguntes: [
        {
          id: "2.1",
          text_pre: "The weather",
          text_post: " last week.",
          opcions: [
            "A is nice",
            "B was nice",
            "C were nice",
            "D nice",
            "E had nice",
          ],
          solucions: ["B"],
          unitats: [10],
        },
        {
          id: "2.2",
          text_pre: "Why",
          text_post: " late this morning?",
          opcions: [
            "A you was",
            "B did you",
            "C was you",
            "D you were",
            "E were you",
          ],
          solucions: ["E"],
          unitats: [10],
        },
        {
          id: "2.3",
          text_pre: "Tony",
          text_post: " in a bank from 2005 to 2011.",
          opcions: ["A work", "B working", "C works", "D worked", "E was work"],
          solucions: ["D"],
          unitats: [11],
        },
        {
          id: "2.4",
          text_pre: "Megan",
          text_post: " to the movies three times last week.",
          opcions: ["A go", "B went", "C goes", "D got", "E was"],
          solucions: ["B"],
          unitats: [11],
        },
        {
          id: "2.5",
          text_pre: "",
          text_post: " TV yesterday.",
          opcions: [
            "A didn't watch",
            "B didn't watched",
            "C wasn't watched",
            "D don't watch",
            "E didn't watching",
          ],
          solucions: ["A"],
          unitats: [12, 22],
        },
        {
          id: "2.6",
          text_pre: '"How',
          text_post: '?" "I don\'t know. I didn\'t see it."',
          opcions: [
            "A happened the accident",
            "B did happen the accident",
            "C does the accident happen",
            "D did the accident happen",
            "E the accident happened",
          ],
          solucions: ["D"],
          unitats: [12, 22],
        },
        {
          id: "2.7",
          text_pre: "What",
          text_post: " at 11:30 yesterday?",
          opcions: [
            "A were you doing",
            "B was you doing",
            "C you were doing",
            "D were you do",
            "E you was doing",
          ],
          solucions: ["A"],
          unitats: [13],
        },
        {
          id: "2.8",
          text_pre: "Jack was reading a book when his phone",
          text_post: "",
          opcions: [
            "A ringing",
            "B ring",
            "C rang",
            "D was ringing",
            "E was ring",
          ],
          solucions: ["C"],
          unitats: [14],
        },
        {
          id: "2.9",
          text_pre: "I saw Emily and Sam this morning. They",
          text_post: " at the bus stop.",
          opcions: [
            "A waiting",
            "B waited",
            "C were waiting",
            "D was waiting",
            "E were waited",
          ],
          solucions: ["C"],
          unitats: [14],
        },
        {
          id: "2.10",
          text_pre: "Dave",
          text_post: " in a factory. Now he works in a supermarket.",
          opcions: [
            "A working",
            "B works",
            "C work",
            "D use to work",
            "E used to work",
          ],
          solucions: ["E"],
          unitats: [15],
        },
      ],
    },
    {
      titol: "Present perfect",
      preguntes: [
        {
          id: "3.1",
          text_pre: "My sister",
          text_post: " by plane.",
          opcions: [
            "A has never travel",
            "B has never traveled",
            "C is never traveled",
            "D has never been traveled",
            "E have never traveled",
          ],
          solucions: ["B"],
          unitats: [16, 22],
        },
        {
          id: "3.2",
          text_pre: "",
          text_post: " that woman before, but I can't remember where.",
          opcions: [
            "A I see",
            "B I seen",
            "C I've saw",
            "D I've seen",
            "E I've seeing",
          ],
          solucions: ["D"],
          unitats: [16, 22],
        },
        {
          id: "3.3",
          text_pre: '"How long',
          text_post: ' married?" "Since 2007."',
          opcions: [
            "A you are",
            "B you have been",
            "C has you been",
            "D are you",
            "E have you been",
          ],
          solucions: ["E"],
          unitats: [17],
        },
        {
          id: "3.4",
          text_pre: '"Do you know Lisa?" "Yes,',
          text_post: ' her for a long time."',
          opcions: ["A I knew", "B I've known", "C I know", "D I am knowing"],
          solucions: ["B"],
          unitats: [17],
        },
        {
          id: "3.5",
          text_pre: "David has been in Canada",
          text_post: ".",
          opcions: [
            "A for six months",
            "B since six months",
            "C six months ago",
            "D in six months",
          ],
          solucions: ["A"],
          unitats: [18, 102],
        },
        {
          id: "3.6",
          text_pre: '"When did Tom leave?"',
          text_post: '."',
          opcions: [
            "A For ten minutes",
            "B Since ten minutes",
            "C Ten minutes ago",
            "D In ten minutes",
          ],
          solucions: ["C"],
          unitats: [18],
        },
        {
          id: "3.7",
          text_pre: "We",
          text_post: " a vacation last year.",
          opcions: [
            "A don't take",
            "B haven't taken",
            "C hasn't taken",
            "D didn't take",
            "E have taken",
          ],
          solucions: ["D"],
          unitats: [19],
        },
        {
          id: "3.8",
          text_pre: "Where",
          text_post: " you on Sunday? I couldn't find you.",
          opcions: [
            "A you have been",
            "B were you",
            "C have you been",
            "D was you",
          ],
          solucions: ["B"],
          unitats: [20, 22],
        },
      ],
    },
    {
      titol: "Passive",
      preguntes: [
        {
          id: "4.1",
          text_pre: "This house",
          text_post: " 100 years ago.",
          opcions: [
            "A is built",
            "B is building",
            "C was building",
            "D was built",
            "E built",
          ],
          solucions: ["D"],
          unitats: [20, 22],
        },
        {
          id: "4.2",
          text_pre: "We",
          text_post: " to the party last week.",
          opcions: [
            "A didn't invite",
            "B didn't invited",
            "C weren't invited",
            "D wasn't invited",
            "E haven't been invited",
          ],
          solucions: ["C"],
          unitats: [20, 22],
        },
        {
          id: "4.3",
          text_pre: '"Where',
          text_post: ' born?" "In Cairo."',
          opcions: [
            "A you are",
            "B you were",
            "C was you",
            "D are you",
            "E were you",
          ],
          solucions: ["E"],
          unitats: [20],
        },
        {
          id: "4.4",
          text_pre: "My car is at the garage. It",
          text_post: "",
          opcions: [
            "A is being repaired",
            "B is repairing",
            "C have been repaired",
            "D repaired",
            "E repairs",
          ],
          solucions: ["A"],
          unitats: [21],
        },
        {
          id: "4.5",
          text_pre: "I don't have my keys.",
          text_post: " last week.",
          opcions: [
            "A They were stolen",
            "B They are stolen",
            "C They've stolen",
            "D They're being stolen",
          ],
          solucions: ["A"],
          unitats: [20],
        },
      ],
    },
    {
      titol: "Verb forms",
      preguntes: [
        {
          id: "5.1",
          text_pre: "It",
          text_post: " so we didn't need an umbrella.",
          opcions: [
            "A wasn't rained",
            "B wasn't rain",
            "C didn't raining",
            "D wasn't raining",
          ],
          solucions: ["D"],
          unitats: [22],
        },
        {
          id: "5.2",
          text_pre: "Somebody",
          text_post: " this window.",
          opcions: ["A has broke", "B broke", "C breaked", "D broken"],
          solucions: ["B"],
          unitats: [23],
        },
      ],
    },
    {
      titol: "Future",
      preguntes: [
        {
          id: "6.1",
          text_pre: "Andrew",
          text_post: " tennis tomorrow.",
          opcions: ["A is playing", "B play", "C plays", "D is play"],
          solucions: ["A"],
          unitats: [24],
        },
        {
          id: "6.2",
          text_pre: "",
          text_post: " out tonight?",
          opcions: [
            "A Are you going",
            "B Are you go",
            "C Do you go",
            "D Go you",
            "E Do you going",
          ],
          solucions: ["A"],
          unitats: [24],
        },
        {
          id: "6.3",
          text_pre: '"What time is the concert tonight?" "It',
          text_post: ' at 7:30."',
          opcions: [
            "A is start",
            "B is starting",
            "C starts",
            "D start",
            "E starting",
          ],
          solucions: ["C"],
          unitats: [24],
        },
        {
          id: "6.4",
          text_pre: "What",
          text_post: " to the wedding next week?",
          opcions: [
            "A are you wearing",
            "B are you going to wear",
            "C do you wear",
            "D you are going to wear",
          ],
          solucions: ["A", "B"],
          unitats: [25],
        },
        {
          id: "6.5",
          text_pre: "",
          text_post: " to the movies on Saturday. Do you want to come with us?",
          opcions: ["A We go", "B We'll go", "C We're going", "D We going"],
          solucions: ["C"],
          unitats: [26],
        },
        {
          id: "6.6",
          text_pre: '"',
          text_post: ' you tomorrow, OK?" "OK, bye."',
          opcions: ["A I call", "B I calling", "C I'm calling", "D I'll call"],
          solucions: ["D"],
          unitats: [26],
        },
        {
          id: "6.7",
          text_pre: "I don't want my car anymore.",
          text_post: " it.",
          opcions: [
            "A I sell",
            "B I'll sell",
            "C I'm going to sell",
            "D I'll selling",
          ],
          solucions: ["C"],
          unitats: [25.26],
        },
      ],
    },
    {
      titol: "Modals, imperative, etc.",
      preguntes: [
        {
          id: "7.1",
          text_pre: "",
          text_post: " to the movies tonight, but I'm not sure.",
          opcions: ["A I'll go", "B I'm going", "C I may go", "D I might go"],
          solucions: ["C", "D"],
          unitats: [27],
        },
        {
          id: "7.2",
          text_pre: '"',
          text_post: ' here?" "Sure."',
          opcions: [
            "A Can I sit",
            "B Do I sit",
            "C May I sit",
            "D Can I to sit",
          ],
          solucions: ["A", "C"],
          unitats: [27, 28],
        },
        {
          id: "7.3",
          text_pre: "I'm having a party next week, but Eric and Rachel",
          text_post: ".",
          opcions: [
            "A can't come",
            "B can't to come",
            "C can't coming",
            "D couldn't come",
          ],
          solucions: ["A"],
          unitats: [28],
        },
        {
          id: "7.4",
          text_pre: "Before Maria came to the United States, she",
          text_post: " understand much English.",
          opcions: ["A can", "B can't", "C not", "D couldn't", "E doesn't"],
          solucions: ["D"],
          unitats: [29],
        },
        {
          id: "7.5",
          text_pre: "It's evening, and you haven't eaten anything all day. You",
          text_post: " hungry.",
          opcions: ["A must", "B can", "C must be", "D can be", "E must to be"],
          solucions: ["C"],
          unitats: [29],
        },
        {
          id: "7.6",
          text_pre: "It's a good movie. You",
          text_post: " go and see it.",
          opcions: [
            "A should to",
            "B should to go",
            "C must to",
            "D should",
            "E have",
          ],
          solucions: ["D"],
          unitats: [30],
        },
        {
          id: "7.7",
          text_pre: "It's a nice day.",
          text_post: " for a walk?",
          opcions: [
            "A Do we go",
            "B We will go",
            "C Should we go",
            "D We go",
            "E Go we",
          ],
          solucions: ["C"],
          unitats: [30],
        },
        {
          id: "7.8",
          text_pre: "What time",
          text_post: " go to the dentist tomorrow?",
          opcions: [
            "A you must",
            "B you have to",
            "C have you to",
            "D do you have to",
          ],
          solucions: ["D"],
          unitats: [31],
        },
        {
          id: "7.9",
          text_pre: "We",
          text_post: " walk home last night. There were no buses.",
          opcions: [
            "A have to",
            "B had to",
            "C must",
            "D must to",
            "E must have",
          ],
          solucions: ["B"],
          unitats: [31],
        },
        {
          id: "7.10",
          text_pre: "We",
          text_post: " wait very long for the bus – it came in a few minutes.",
          opcions: [
            "A don't have to",
            "B hadn't to",
            "C didn't have to",
            "D didn't had to",
            "E mustn't",
          ],
          solucions: ["C"],
          unitats: [31],
        },
        {
          id: "7.11",
          text_pre: '"',
          text_post: ' some coffee?" "No, thank you."',
          opcions: [
            "A Are you liking",
            "B You like",
            "C Would you like",
            "D Do you like",
          ],
          solucions: ["C"],
          unitats: [32],
        },
        {
          id: "7.12",
          text_pre: "I don't really want to go out.",
          text_post: " home.",
          opcions: [
            "A I rather stay",
            "B I'd rather stay",
            "C I'd rather to stay",
            "D I'd prefer to stay",
          ],
          solucions: ["B", "D"],
          unitats: [33],
        },
        {
          id: "7.13",
          text_pre: "Please",
          text_post: " Stay here with me.",
          opcions: ["A don't go", "B you no go", "C go not", "D you don't go"],
          solucions: ["A"],
          unitats: [34],
        },
        {
          id: "7.14",
          text_pre: "It's a nice day.",
          text_post: " out.",
          opcions: ["A Let's to go", "B Let's go", "C Let's going", "D We go"],
          solucions: ["B"],
          unitats: [34],
        },
      ],
    },
    {
      titol: "There and it",
      preguntes: [
        {
          id: "8.1",
          text_pre: "Excuse me,",
          text_post: " a hotel near here?",
          opcions: ["A has there", "B is there", "C there is", "D is it"],
          solucions: ["B"],
          unitats: [35],
        },
        {
          id: "8.2",
          text_pre: "",
          text_post: " a lot of accidents on this road. It's very dangerous.",
          opcions: [
            "A Have",
            "B It has",
            "C There have",
            "D They are",
            "E There are",
          ],
          solucions: ["E"],
          unitats: [35],
        },
        {
          id: "8.3",
          text_pre: "I was hungry when I got home, but",
          text_post: " anything to eat.",
          opcions: [
            "A there wasn't",
            "B there weren't",
            "C it wasn't",
            "D there hasn't been",
          ],
          solucions: ["A"],
          unitats: [36],
        },
        {
          id: "8.4",
          text_pre: "",
          text_post: " two miles from our house to downtown.",
          opcions: ["A It's", "B It has", "C There is", "D There are"],
          solucions: ["A"],
          unitats: [37],
        },
        {
          id: "8.5",
          text_pre: "",
          text_post: " true that you're moving to Dallas?",
          opcions: ["A Is there", "B Is it", "C Is", "D Are you"],
          solucions: ["B"],
          unitats: [37],
        },
      ],
    },
    {
      titol: "Auxiliary verbs",
      preguntes: [
        {
          id: "9.1",
          text_pre: "I haven't seen the movie, but my sister",
          text_post: ".",
          opcions: ["A does", "B is", "C has seen", "D has", "E hasn't"],
          solucions: ["D"],
          unitats: [38],
        },
        {
          id: "9.2",
          text_pre: "I don't like hot weather, but Sue",
          text_post: ".",
          opcions: ["A does", "B doesn't", "C do", "D does like", "E likes"],
          solucions: ["A"],
          unitats: [38],
        },
        {
          id: "9.3",
          text_pre: '"Nicole got married last week."',
          text_post: ' "Really?"',
          opcions: ["A Got she", "B She got", "C She did", "D She has"],
          solucions: ["C"],
          unitats: [39],
        },
        {
          id: "9.4",
          text_pre: "You haven't met my mother,",
          text_post: "?",
          opcions: [
            "A haven't you",
            "B have you",
            "C did you",
            "D you have",
            "E you haven't",
          ],
          solucions: ["B"],
          unitats: [39],
        },
        {
          id: "9.5",
          text_pre: "Bill doesn't watch TV. He doesn't read newspapers,",
          text_post: ".",
          opcions: ["A too", "B either", "C neither", "D never"],
          solucions: ["B"],
          unitats: [40],
        },
        {
          id: "9.6",
          text_pre: '"I\'d like to go to Australia."',
          text_post: ".",
          opcions: [
            "A So do I",
            "B So am I",
            "C So would I",
            "D Neither do I",
            "E So I would",
          ],
          solucions: ["C"],
          unitats: [40],
        },
        {
          id: "9.7",
          text_pre: "Sue",
          text_post: " much on weekends.",
          opcions: ["A don't", "B doesn't", "C don't do", "D doesn't do"],
          solucions: ["D"],
          unitats: [41],
        },
      ],
    },
    {
      titol: "Questions",
      preguntes: [
        {
          id: "10.1",
          text_pre: '"When',
          text_post: '?" "I\'m not sure. More than 100 years ago."',
          opcions: [
            "A did the telephone invent",
            "B has the telephone invented",
            "C was invented the telephone",
            "D was the telephone invented",
            "E the telephone was invented",
          ],
          solucions: ["D"],
          unitats: [42],
        },
        {
          id: "10.2",
          text_pre: '"I broke my finger last week." "How',
          text_post: ' that?"',
          opcions: ["A did you", "B you did", "C you did do", "D did you do"],
          solucions: ["D"],
          unitats: [42],
        },
        {
          id: "10.3",
          text_pre: "Why",
          text_post: " me last night? I was waiting for you to call.",
          opcions: [
            "A didn't you call",
            "B you not call",
            "C you don't call",
            "D you didn't call",
          ],
          solucions: ["A"],
          unitats: [42],
        },
        {
          id: "10.4",
          text_pre: '"Who',
          text_post: ' in this house?" "I don\'t know."',
          opcions: ["A lives", "B does live", "C does lives", "D living"],
          solucions: ["A"],
          unitats: [43],
        },
        {
          id: "10.5",
          text_pre: "What",
          text_post: " when you told him the story?",
          opcions: [
            "A said Kevin",
            "B did Kevin say",
            "C Kevin said",
            "D did Kevin said",
          ],
          solucions: ["B"],
          unitats: [43],
        },
        {
          id: "10.6",
          text_pre: '"Tom\'s father is in the hospital." "',
          text_post: '"',
          opcions: [
            "A In which hospital he is?",
            "B In which hospital he is in?",
            "C Which hospital he is in?",
            "D Which hospital is he in?",
          ],
          solucions: ["D"],
          unitats: [44],
        },
        {
          id: "10.7",
          text_pre: 'Did you have a good vacation? "',
          text_post: '"',
          opcions: [
            "A How was the weather like?",
            "B What was the weather like?",
            "C What the weather was like?",
            "D Was the weather like?",
          ],
          solucions: ["B"],
          unitats: [44],
        },
        {
          id: "10.8",
          text_pre: "",
          text_post: " taller – Joe or David?",
          opcions: ["A Who is", "B What is", "C Which is", "D Who has"],
          solucions: ["A"],
          unitats: [45],
        },
        {
          id: "10.9",
          text_pre: "There are four umbrellas here.",
          text_post: " is yours?",
          opcions: ["A What", "B Who", "C Which", "D How", "E Which one"],
          solucions: ["C", "E"],
          unitats: [45, 73],
        },
        {
          id: "10.10",
          text_pre: "How long",
          text_post: " to cross the Atlantic by ship?",
          opcions: [
            "A is it",
            "B does it need",
            "C does it take",
            "D does it want",
          ],
          solucions: ["C"],
          unitats: [46],
        },
        {
          id: "10.11",
          text_pre: "I don't remember what",
          text_post: " at the party.",
          opcions: [
            "A Anna was wearing",
            "B was wearing Anna",
            "C was Anna wearing",
            "D does it want",
          ],
          solucions: ["A"],
          unitats: [47],
        },
        {
          id: "10.12",
          text_pre: "Do you know",
          text_post: " ? Yes, I Think so",
          opcions: [
            "A if Jack is home",
            "B is Jack home",
            "C whether Jack is home",
            "D that jack is home",
          ],
          solucions: ["A,C"],
          unitats: [47],
        },
      ],
    },
    {
      titol: "Reported speech",
      preguntes: [
        {
          id: "11.1",
          text_pre: "I saw Eric a week ago. He said that",
          text_post: " me, but he didn't.",
          opcions: [
            "A he call",
            "B he calls",
            "C he'll call",
            "D he's going to call",
            "E he would call",
          ],
          solucions: ["E"],
          unitats: [48],
        },
        {
          id: "11.2",
          text_pre: '"Why did Tim go to bed so early?" "He',
          text_post: '."',
          opcions: [
            "A said he was tired",
            "B said that he was tired",
            "C said me he was tired",
            "D told me he was tired",
            "E told that he was tired",
          ],
          solucions: ["A", "B", "D"],
          unitats: [48],
        },
      ],
    },
    {
      titol: "-ing and to ...",
      preguntes: [
        {
          id: "12.1",
          text_pre: "You shouldn't",
          text_post: " so hard.",
          opcions: ["A working", "B work", "C to work", "D worked"],
          solucions: ["B"],
          unitats: [49],
        },
        {
          id: "12.2",
          text_pre: "It's late. I",
          text_post: " now.",
          opcions: [
            "A must to go",
            "B have go",
            "C have to going",
            "D have to go",
          ],
          solucions: ["D"],
          unitats: [49],
        },
        {
          id: "12.3",
          text_pre: "Rachel decided",
          text_post: " her car.",
          opcions: ["A sell", "B to sell", "C selling", "D to selling"],
          solucions: ["B"],
          unitats: [50],
        },
        {
          id: "12.4",
          text_pre: "I don't mind",
          text_post: " early.",
          opcions: [
            "A get up",
            "B to get up",
            "C getting up",
            "D to getting up",
          ],
          solucions: ["C"],
          unitats: [50],
        },
        {
          id: "12.5",
          text_pre: "Do you like",
          text_post: " early?",
          opcions: [
            "A get up",
            "B to get up",
            "C getting up",
            "D to getting up",
          ],
          solucions: ["B", "C"],
          unitats: [50],
        },
        {
          id: "12.6",
          text_pre: "Do you want",
          text_post: " you some money?",
          opcions: [
            "A me lend",
            "B me lending",
            "C me to lend",
            "D that I lend",
          ],
          solucions: ["C"],
          unitats: [51],
        },
        {
          id: "12.7",
          text_pre: "He's very funny. He makes",
          text_post: ".",
          opcions: [
            "A me laugh",
            "B me laughing",
            "C me to laugh",
            "D that I laugh",
          ],
          solucions: ["A"],
          unitats: [51],
        },
        {
          id: "12.8",
          text_pre: "Sofia went to the store",
          text_post: " some fruit.",
          opcions: [
            "A for get",
            "B for to get",
            "C for getting",
            "D to get",
            "E get",
          ],
          solucions: ["D"],
          unitats: [52],
        },
      ],
    },
    {
      titol: "Go, get, do, make, have",
      preguntes: [
        {
          id: "13.1",
          text_pre: "The water looks nice. I'm going",
          text_post: ".",
          opcions: [
            "A for a swim",
            "B on a swim",
            "C to swimming",
            "D swimming",
          ],
          solucions: ["A", "D"],
          unitats: [53],
        },
        {
          id: "13.2",
          text_pre: "I'm sorry your mother is sick. I hope she",
          text_post: " better soon.",
          opcions: ["A has", "B makes", "C gets", "D goes"],
          solucions: ["C"],
          unitats: [54],
        },
        {
          id: "13.3",
          text_pre: "Kate",
          text_post: " the car and drove away.",
          opcions: ["A went into", "B went in", "C got in", "D got into"],
          solucions: ["C", "D"],
          unitats: [54],
        },
        {
          id: "13.4",
          text_pre: '"Should I open the window?" "No, it\'s OK. I\'ll',
          text_post: ' it."',
          opcions: ["A do", "B make", "C get", "D open"],
          solucions: ["A", "D"],
          unitats: [55],
        },
        {
          id: "13.5",
          text_pre: "I'm sorry.",
          text_post: " a mistake.",
          opcions: ["A did", "B made", "C got", "D had"],
          solucions: ["B"],
          unitats: [55],
        },
        {
          id: "13.6",
          text_pre: "",
          text_post: " enough time to do everything you wanted to do?",
          opcions: [
            "A Have you",
            "B Had you",
            "C Do you have",
            "D Did you have",
          ],
          solucions: ["D"],
          unitats: [56],
        },
      ],
    },
    {
      titol: "Pronouns and possessives",
      preguntes: [
        {
          id: "14.1",
          text_pre: "I don't want this book. You can have",
          text_post: ".",
          opcions: ["A it", "B them", "C her", "D him"],
          solucions: ["A"],
          unitats: [57, 60],
        },
        {
          id: "14.2",
          text_pre:
            "Sue and Kevin are going to the movies. Do you want to go with",
          text_post: "?",
          opcions: ["A her", "B they", "C them", "D him"],
          solucions: ["C"],
          unitats: [57, 60],
        },
        {
          id: "14.3",
          text_pre: "I know Amy, but I don't know",
          text_post: " husband.",
          opcions: ["A their", "B his", "C she", "D her"],
          solucions: ["D"],
          unitats: [58, 60],
        },
        {
          id: "14.4",
          text_pre: "Hawaii is famous for",
          text_post: " beaches.",
          opcions: ["A his", "B its", "C it's", "D their"],
          solucions: ["B"],
          unitats: [58],
        },
        {
          id: "14.5",
          text_pre: "I didn't have an umbrella, so Emily gave me",
          text_post: ".",
          opcions: ["A her", "B hers", "C her umbrella", "D she's"],
          solucions: ["B", "C"],
          unitats: [59, 60],
        },
        {
          id: "14.6",
          text_pre: "I went to the movies with a friend of",
          text_post: ".",
          opcions: ["A mine", "B my", "C me", "D myself"],
          solucions: ["A"],
          unitats: [59, 60],
        },
        {
          id: "14.7",
          text_pre: "We had a good vacation. We enjoyed",
          text_post: ".",
          opcions: ["A us", "B our", "C ours", "D ourself", "E ourselves"],
          solucions: ["E"],
          unitats: [61],
        },
        {
          id: "14.8",
          text_pre: "Kate and Nicole are good friends. They know",
          text_post: " well.",
          opcions: ["A each other", "B them", "C themselves", "D theirselves"],
          solucions: ["A"],
          unitats: [61],
        },
        {
          id: "14.9",
          text_pre: "Have you met",
          text_post: "?",
          opcions: [
            "A the wife of Mr. Black",
            "B Mr. Black wife",
            "C the wife Mr. Black",
            "D Mr. Black's wife",
            "E the Mr. Black's wife",
          ],
          solucions: ["D"],
          unitats: [62],
        },
        {
          id: "14.10",
          text_pre: "Have you seen",
          text_post: "?",
          opcions: [
            "A the car of my parents",
            "B my parent's car",
            "C my parents' car",
            "D my parents car",
          ],
          solucions: ["C"],
          unitats: [62],
        },
      ],
    },
    {
      titol: "A and the",
      preguntes: [
        {
          id: "15.1",
          text_pre: "I'm going to buy",
          text_post: ".",
          opcions: [
            "A hat and umbrella",
            "B a hat and a umbrella",
            "C a hat and an umbrella",
            "D an hat and an umbrella",
          ],
          solucions: ["C"],
          unitats: [63, 65],
        },
        {
          id: "15.2",
          text_pre: '"What do you do?" "',
          text_post: '"',
          opcions: [
            "A I dentist",
            "B I'm a dentist",
            "C I'm dentist",
            "D I do dentist",
          ],
          solucions: ["B"],
          unitats: [63],
        },
        {
          id: "15.3",
          text_pre: "I'm going shopping. I need",
          text_post: ".",
          opcions: [
            "A some new jeans",
            "B a new jeans",
            "C a new pair of jeans",
            "D a new pair jeans",
          ],
          solucions: ["A", "C"],
          unitats: [64],
        },
        {
          id: "15.4",
          text_pre: "I like the people here.",
          text_post: " very friendly.",
          opcions: [
            "A She is",
            "B They are",
            "C They is",
            "D It is",
            "E He is",
          ],
          solucions: ["B"],
          unitats: [64],
        },
        {
          id: "15.5",
          text_pre: "We can't get into the house without",
          text_post: ".",
          opcions: ["A some key", "B a key", "C key"],
          solucions: ["B"],
          unitats: [65],
        },
        {
          id: "15.6",
          text_pre: "Where can I get",
          text_post: " about hotels here?",
          opcions: [
            "A some information",
            "B some informations",
            "C an information",
          ],
          solucions: ["A"],
          unitats: [66],
        },
        {
          id: "15.7",
          text_pre: "We enjoyed our vacation.",
          text_post: " was very nice.",
          opcions: ["A Hotel", "B A hotel", "C An hotel", "D The hotel"],
          solucions: ["D"],
          unitats: [67, 68],
        },
        {
          id: "15.8",
          text_pre: "The table is in",
          text_post: ".",
          opcions: [
            "A middle of room",
            "B middle of the room",
            "C the middle of the room",
            "D the middle of room",
          ],
          solucions: ["C"],
          unitats: [68],
        },
        {
          id: "15.9",
          text_pre: "What did you have for",
          text_post: "?",
          opcions: ["A the breakfast", "B breakfast", "C a breakfast"],
          solucions: ["B"],
          unitats: [68],
        },
        {
          id: "15.10",
          text_pre: "I finish",
          text_post: " at 5:00 every day.",
          opcions: ["A the work", "B work", "C a work"],
          solucions: ["B"],
          unitats: [68],
        },
        {
          id: "15.11",
          text_pre: "I'm tired. I'm going",
          text_post: ".",
          opcions: [
            "A in bed",
            "B in the bed",
            "C to a bed",
            "D to the bed",
            "E to bed",
          ],
          solucions: ["E"],
          unitats: [69],
        },
        {
          id: "15.12",
          text_pre: "We don't eat",
          text_post: " very often.",
          opcions: ["A the meat", "B some meat", "C a meat", "D meat"],
          solucions: ["D"],
          unitats: [70],
        },
        {
          id: "15.13",
          text_pre: "",
          text_post: " is in New York.",
          opcions: ["A The Times Square", "B Times Square"],
          solucions: ["B"],
          unitats: [71],
        },
        {
          id: "15.14",
          text_pre: "My friends are staying at",
          text_post: ".",
          opcions: ["A the Regent Hotel", "B Regent Hotel"],
          solucions: ["A"],
          unitats: [71],
        },
      ],
    },
    {
      titol: "Determiners and pronouns",
      preguntes: [
        {
          id: "16.1",
          text_pre: '"I\'m going on vacation next week." "Oh,',
          text_post: ' nice."',
          opcions: ["A it's", "B this is", "C that's"],
          solucions: ["C"],
          unitats: [73],
        },
        {
          id: "16.2",
          text_pre: '"Is there a bank near here?" "Yes, there\'s',
          text_post: ' on the corner."',
          opcions: ["A some", "B it", "C one", "D a one"],
          solucions: ["C"],
          unitats: [73],
        },
        {
          id: "16.3",
          text_pre: "This cup is dirty. Can I have",
          text_post: "?",
          opcions: ["A clean one", "B a clean one", "C clean", "D a clean"],
          solucions: ["B"],
          unitats: [73],
        },
        {
          id: "16.4",
          text_pre: "I'm going shopping. I'm going to buy",
          text_post: " clothes.",
          opcions: ["A any", "B some"],
          solucions: ["B"],
          unitats: [74],
        },
        {
          id: "16.5",
          text_pre: '"Where\'s your luggage?" "I don\'t have',
          text_post: '."',
          opcions: ["A one", "B some", "C any"],
          solucions: ["C"],
          unitats: [74],
        },
        {
          id: "16.6",
          text_pre: "Tracey and Jeff",
          text_post: ".",
          opcions: [
            "A have no children",
            "B don't have no children",
            "C don't have any children",
            "D have any children",
          ],
          solucions: ["A", "C"],
          unitats: [75, 76],
        },
        {
          id: "16.7",
          text_pre: '"How much money do you have?" "',
          text_post: '."',
          opcions: ["A No", "B No one", "C Any", "D None"],
          solucions: ["D"],
          unitats: [75],
        },
        {
          id: "16.8",
          text_pre: "There is",
          text_post: " in the room. It's empty.",
          opcions: ["A anybody", "B nobody", "C anyone", "D no one"],
          solucions: ["B", "D"],
          unitats: [76, 77],
        },
        {
          id: "16.9",
          text_pre: '"What did you say?" "',
          text_post: '."',
          opcions: ["A Nothing", "B Nobody", "C Anything", "D Anybody"],
          solucions: ["A"],
          unitats: [76, 77],
        },
        {
          id: "16.10",
          text_pre: "I'm hungry. I want",
          text_post: ".",
          opcions: [
            "A something for eat",
            "B something to eat",
            "C something for eating",
          ],
          solucions: ["B"],
          unitats: [77],
        },
        {
          id: "16.11",
          text_pre: "It rained",
          text_post: " last week.",
          opcions: ["A all day", "B all days", "C every days", "D every day"],
          solucions: ["D"],
          unitats: [78],
        },
        {
          id: "16.12",
          text_pre: "",
          text_post: " children like to play.",
          opcions: [
            "A Everybody need",
            "B Everybody needs",
            "C Everyone need",
            "D Everyone needs",
          ],
          solucions: ["B", "D"],
          unitats: [78],
        },
        {
          id: "16.13",
          text_pre: "",
          text_post: " children like to play.",
          opcions: ["A Most", "B The most", "C Most of", "D The most of"],
          solucions: ["A"],
          unitats: [79],
        },
        {
          id: "16.14",
          text_pre: "I like",
          text_post: ".",
          opcions: ["A both", "B both of", "C either", "D either of"],
          solucions: ["A", "B"],
          unitats: [80],
        },
        {
          id: "16.15",
          text_pre: "I haven't read",
          text_post: " these books.",
          opcions: ["A neither", "B neither of", "C either", "D either of"],
          solucions: ["D"],
          unitats: [80],
        },
        {
          id: "16.16",
          text_pre: "Do you have",
          text_post: " friends?",
          opcions: ["A a lot of", "B much", "C many", "D much of", "E many of"],
          solucions: ["A", "C"],
          unitats: [81],
        },
        {
          id: "16.17",
          text_pre: "We like movies, so we go to the movies",
          text_post: ".",
          opcions: ["A a lot of", "B much", "C many", "D a lot"],
          solucions: ["D"],
          unitats: [81],
        },
        {
          id: "16.18",
          text_pre: "There were",
          text_post: " people in the theater. It was almost empty.",
          opcions: ["A a little", "B few", "C little", "D a few of"],
          solucions: ["B"],
          unitats: [82],
        },
        {
          id: "16.19",
          text_pre: "They have",
          text_post: " money, so they're not poor.",
          opcions: [
            "A a little",
            "B a few",
            "C few",
            "D little",
            "E little of",
          ],
          solucions: ["A"],
          unitats: [82],
        },
      ],
    },
    {
      titol: "Adjectives and adverbs",
      preguntes: [
        {
          id: "17.1",
          text_pre: "I don’t speak any",
          text_post: ".",
          opcions: [
            "A foreign languages",
            "B languages foreign",
            "C languages foreigns",
          ],
          solucions: ["A"],
          unitats: [83],
        },
        {
          id: "17.2",
          text_pre: "He ate his dinner very",
          text_post: ".",
          opcions: ["A quick", "B quicker", "C quickly"],
          solucions: ["C"],
          unitats: [83],
        },
        {
          id: "17.3",
          text_pre: "You speak English very",
          text_post: ".",
          opcions: ["A good", "B fluent", "C well", "D slow"],
          solucions: ["C"],
          unitats: [84],
        },
        {
          id: "17.4",
          text_pre: "Helen wants",
          text_post: ".",
          opcions: [
            "A a more big car",
            "B a car more big",
            "C a car bigger",
            "D a bigger car",
          ],
          solucions: ["D"],
          unitats: [85],
        },
        {
          id: "17.5",
          text_pre: "“Do you feel better today?” “No, I feel",
          text_post: ".”",
          opcions: ["A good", "B worse", "C more bad", "D more worse"],
          solucions: ["B"],
          unitats: [86],
        },
        {
          id: "17.6",
          text_pre: "Athens is older",
          text_post: " Rome.",
          opcions: ["A as", "B than", "C that", "D of"],
          solucions: ["B"],
          unitats: [86],
        },
        {
          id: "17.7",
          text_pre: "I can run faster",
          text_post: ".",
          opcions: [
            "A than him",
            "B that he can",
            "C than he can",
            "D as he can",
            "E as he",
          ],
          solucions: ["A,C"],
          unitats: [86],
        },
        {
          id: "17.8",
          text_pre: "Tennis isn’t",
          text_post: " soccer.",
          opcions: [
            "A popular as",
            "B popular than",
            "C as popular than",
            "D so popular that",
            "E as popular as",
          ],
          solucions: ["E"],
          unitats: [87],
        },
        {
          id: "17.9",
          text_pre: "The weather today is the same",
          text_post: " yesterday.",
          opcions: ["A as", "B that", "C than", "D like"],
          solucions: ["A"],
          unitats: [87],
        },
        {
          id: "17.10",
          text_pre: "The Best West Motel is",
          text_post: " in town.",
          opcions: [
            "A the more expensive motel",
            "B the most expensive motel",
            "C the motel most expensive",
            "D the motel the more expensive",
            "E the motel more expensive",
          ],
          solucions: ["B"],
          unitats: [88],
        },
        {
          id: "17.11",
          text_pre: "The movie was very bad. I think it’s the",
          text_post: " movie I’ve ever seen.",
          opcions: [
            "A worse",
            "B baddest",
            "C most bad",
            "D worst",
            "E more worse",
          ],
          solucions: ["D"],
          unitats: [88],
        },
        {
          id: "17.12",
          text_pre: "Why don’t you buy a car? You’ve got",
          text_post: ".",
          opcions: ["A enough money", "B money enough", "C enough of money"],
          solucions: ["A"],
          unitats: [89],
        },
        {
          id: "17.13",
          text_pre: "Is your English",
          text_post: " a conversation?",
          opcions: [
            "A enough good to have",
            "B good enough for have",
            "C enough good for",
            "D good enough to have",
          ],
          solucions: ["D"],
          unitats: [89],
        },
        {
          id: "17.14",
          text_pre: "I’m",
          text_post: " out.",
          opcions: [
            "A too tired for go",
            "B too much tired for going",
            "C too tired to go",
            "D too much tired to go",
          ],
          solucions: ["C"],
          unitats: [90],
        },
      ],
    },
    {
      titol: "Word order",
      preguntes: [
        {
          id: "18.1",
          text_pre: "Sue",
          text_post: " They're very nice.",
          opcions: [
            "A bought yesterday some new shoes",
            "B bought some new shoes yesterday",
            "C yesterday bought some new shoes",
          ],
          solucions: ["B"],
          unitats: [91],
        },
        {
          id: "18.2",
          text_pre: "",
          text_post: " coffee in the morning.",
          opcions: ["A I drink always", "B Always I drink", "C I always drink"],
          solucions: ["C"],
          unitats: [91],
        },
        {
          id: "18.3",
          text_pre: "",
          text_post: " during the day.",
          opcions: [
            "A They are at home never",
            "B They are never at home",
            "C They never are at home",
            "D Never they are at home",
          ],
          solucions: ["B"],
          unitats: [92],
        },
        {
          id: "18.4",
          text_pre: '"Where\'s Emma?" "She',
          text_post: '"',
          opcions: [
            "A isn't here yet",
            "B isn't here already",
            "C isn't here still",
          ],
          solucions: ["A"],
          unitats: [93],
        },
        {
          id: "18.5",
          text_pre: "I locked the door, and I gave",
          text_post: ".",
          opcions: [
            "A Sarah the keys",
            "B to Sarah the keys",
            "C the keys Sarah",
            "D the keys to Sarah",
          ],
          solucions: ["A,D"],
          unitats: [94],
        },
      ],
    },
    {
      titol: "Conjunctions and clauses",
      preguntes: [
        {
          id: "19.1",
          text_pre: "I can't talk to you now. I'll talk to you later when",
          text_post: " more time.",
          opcions: [
            "A I'll have",
            "B I had",
            "C I have",
            "D I'm going to have",
          ],
          solucions: ["C"],
          unitats: [94],
        },
        {
          id: "19.2",
          text_pre: "",
          text_post: " late tonight, don't wait for me.",
          opcions: ["A If I'm", "B If I'll be", "C When I'm", "D When I'll be"],
          solucions: ["A"],
          unitats: [94],
        },
        {
          id: "19.3",
          text_pre: "I don't know the answer. If I",
          text_post: " the answer, I'd tell you.",
          opcions: ["A know", "B would know", "C have known", "D knew"],
          solucions: ["D"],
          unitats: [95],
        },
        {
          id: "19.4",
          text_pre: "I like that jacket.",
          text_post: " it if it wasn't so expensive.",
          opcions: [
            "A I buy",
            "B I'll buy",
            "C I bought",
            "D I'd bought",
            "E I'd buy",
          ],
          solucions: ["E"],
          unitats: [95],
        },
        {
          id: "19.5",
          text_pre: "Emma lives in a house",
          text_post: " is 100 years old.",
          opcions: ["A who", "B that", "C which", "D it", "E what"],
          solucions: ["B", "C"],
          unitats: [96],
        },
        {
          id: "19.6",
          text_pre: "The people",
          text_post: " work in the office are very friendly.",
          opcions: ["A who", "B that", "C they", "D which", "E what"],
          solucions: ["A", "B"],
          unitats: [96],
        },
        {
          id: "19.7",
          text_pre: "Did you find the books",
          text_post: "?",
          opcions: [
            "A who you wanted",
            "B that you wanted",
            "C what you wanted",
            "D you wanted",
            "E you wanted it",
          ],
          solucions: ["B", "D"],
          unitats: [96],
        },
        {
          id: "19.8",
          text_pre: "I met",
          text_post: " can speak six languages.",
          opcions: [
            "A a woman who",
            "B a woman which",
            "C a woman",
            "D a woman she",
          ],
          solucions: ["A"],
          unitats: [97],
        },
      ],
    },
    {
      titol: "Prepositions",
      preguntes: [
        {
          id: "20.1",
          text_pre: "Bye! See you",
          text_post: ".",
          opcions: ["A Friday", "B at Friday", "C in Friday", "D on Friday"],
          solucions: ["D"],
          unitats: [101],
        },
        {
          id: "20.2",
          text_pre: "Hurry! The train leaves",
          text_post: " five minutes.",
          opcions: ["A at", "B on", "C from", "D after", "E in"],
          solucions: ["E"],
          unitats: [101],
        },
        {
          id: "20.3",
          text_pre: "“How long will you be away?” “",
          text_post: " Monday.”",
          opcions: ["A On", "B To", "C Until", "D Till", "E Since"],
          solucions: ["C", "D"],
          unitats: [102],
        },
        {
          id: "20.4",
          text_pre: "We played basketball yesterday. We played",
          text_post: " two hours.",
          opcions: ["A in", "B for", "C since", "D during"],
          solucions: ["B"],
          unitats: [103],
        },
        {
          id: "20.5",
          text_pre: "I always have breakfast before",
          text_post: " to work.",
          opcions: ["A I go", "B go", "C to go", "D going"],
          solucions: ["A", "D"],
          unitats: [103],
        },
        {
          id: "20.6",
          text_pre: "Write your name",
          text_post: " the top of the page.",
          opcions: ["A at", "B on", "C in", "D to"],
          solucions: ["B"],
          unitats: [104],
        },
        {
          id: "20.7",
          text_pre: "There are a lot of apples",
          text_post: " those trees.",
          opcions: ["A at", "B on", "C in", "D to"],
          solucions: ["C"],
          unitats: [104],
        },
        {
          id: "20.8",
          text_pre: "What’s the largest city",
          text_post: " the world?",
          opcions: ["A at", "B on", "C in", "D of"],
          solucions: ["C"],
          unitats: [105],
        },
        {
          id: "20.9",
          text_pre: "The office is",
          text_post: " the second floor.",
          opcions: ["A at", "B on", "C in", "D to"],
          solucions: ["B"],
          unitats: [105],
        },
        {
          id: "20.10",
          text_pre: "I met a lot of people",
          text_post: " the party.",
          opcions: ["A on", "B to", "C in", "D at"],
          solucions: ["D"],
          unitats: [106],
        },
        {
          id: "20.11",
          text_pre: "I want to go",
          text_post: " Mexico next year.",
          opcions: ["A at", "B on", "C in", "D to"],
          solucions: ["D"],
          unitats: [106],
        },
        {
          id: "20.12",
          text_pre: "What time did you arrive",
          text_post: " the hotel?",
          opcions: ["A at", "B on", "C in", "D to"],
          solucions: ["A"],
          unitats: [106],
        },
        {
          id: "20.13",
          text_pre: "“Where is Dan in this picture?” “He’s",
          text_post: " Ben.”",
          opcions: [
            "A at front of",
            "B in the front of",
            "C in front of",
            "D in front from",
          ],
          solucions: ["C"],
          unitats: [107],
        },
        {
          id: "20.14",
          text_pre: "I jumped",
          text_post: " the wall into the yard.",
          opcions: ["A on", "B through", "C across", "D over", "E above"],
          solucions: ["D"],
          unitats: [108],
        },
        {
          id: "20.15",
          text_pre: "Megan isn't at work this week. She's",
          text_post: " vacation.",
          opcions: ["A on", "B in", "C for", "D to", "E at"],
          solucions: ["A"],
          unitats: [109],
        },
        {
          id: "20.16",
          text_pre: "Do you like traveling",
          text_post: "?",
          opcions: [
            "A with train",
            "B with the train",
            "C in train",
            "D on train",
            "E by train",
          ],
          solucions: ["E"],
          unitats: [109],
        },
        {
          id: "20.17",
          text_pre: "I'm not very good",
          text_post: " telling stories.",
          opcions: ["A on", "B with", "C at", "D in", "E for"],
          solucions: ["C"],
          unitats: [110],
        },
        {
          id: "20.18",
          text_pre: "Tom left without",
          text_post: " goodbye.",
          opcions: ["A say", "B saying", "C to say", "D that he said"],
          solucions: ["B"],
          unitats: [1110],
        },
        {
          id: "20.19",
          text_pre: "I have to call",
          text_post: " tonight.",
          opcions: [
            "A with my parents",
            "B to my parents",
            "C at my parents",
            "D my parents",
          ],
          solucions: ["D"],
          unitats: [111],
        },
        {
          id: "20.20",
          text_pre:
            "“Do you like eating in restaurants?” “Sometimes. It depends",
          text_post: " the restaurant.”",
          opcions: ["A in", "B at", "C of", "D on", "E over"],
          solucions: ["D"],
          unitats: [111],
        },
      ],
    },
    {
      titol: "Phrasal verbs",
      preguntes: [
        {
          id: "21.1",
          text_pre: "A car stopped and a woman got",
          text_post: ".",
          opcions: ["A off", "B down", "C out", "D out of"],
          solucions: ["C"],
          unitats: [105],
        },
        {
          id: "21.2",
          text_pre: "It was cold, so I",
          text_post: ".",
          opcions: [
            "A put on my coat",
            "B put my coat on",
            "C put the coat on me",
            "D put me the coat on",
          ],
          solucions: ["A", "B"],
          unitats: [105],
        },
        {
          id: "21.3",
          text_pre: "I have Rachel's keys. I have to",
          text_post: " to her.",
          opcions: [
            "A give back",
            "B give them back",
            "C give back them",
            "D give it back",
          ],
          solucions: ["B"],
          unitats: [105],
        },
      ],
    },
  ],
};
