// Fitxer: dades.js
// 1. DICCIONARI COMPLET D'UNITATS (Extret del fitxer)
const diccionariUnitats = {
  1: "Present continuous (I am doing)",
  2: "Present simple (I do)",
  3: "Present continuous and present simple 1 (I am doing and I do)",
  4: "Present continuous and present simple 2 (I am doing and I do)",
  5: "Past simple (I did)",
  6: "Past continuous (I was doing)",

  7: "Present perfect 1 (I have done)",
  8: "Present perfect 2 (I have done)",
  9: "Present perfect continuous (I have been doing)",
  10: "Present perfect continuous and simple (I have been doing and I have done)",
  11: "how long have you (been) ... ?",
  12: "for and since / when ... ? and how long ... ?",
  13: "Present perfect and past 1 (I have done and I did)",
  14: "Present perfect and past 2 (I have done and I did)",
  15: "Past perfect (I had done)",
  16: "Past perfect continuous (I had been doing)",
  17: "have and have got",
  18: "used to (do)",

  19: "Present tenses (I am doing / I do) for the future",
  20: "I'm going to (do)",
  21: "will and shall 1",
  22: "will and shall 2",
  23: "I will and I'm going to",
  24: "will be doing and will have done",
  25: "when I do and when I've done / if and when",

  26: "can, could and (be) able to",
  27: "could (do) and could have (done)",
  28: "must and can't",
  29: "may and might 1",
  30: "may and might 2",
  31: "have to and must",
  32: "must / mustn't / needn't",
  33: "should 1",
  34: "should 2",
  35: "I'd better ... / it's time ...",
  36: "would",
  37: "can/could/would you ... ? (Requests, offers, permission, invitations)",

  38: "if I do ... and if I did ...",
  39: "if I knew ... / I wish I knew ...",
  40: "if I had known ... / I wish I had known ...",
  41: "wish",

  42: "Passive 1 (is done / was done)",
  43: "Passive 2 (be done / been done / being done)",
  44: "Passive 3",
  45: "it is said that ... / he is said to ... / he is supposed to ...",
  46: "have something done",

  47: "Reported speech 1 (he said that ...)",
  48: "Reported speech 2",

  49: "Questions 1",
  50: "Questions 2 (do you know where ... ? / he asked me where ...)",
  51: "Auxiliary verbs (have/do/can etc.) / I think so / I hope so",
  52: "Question tags (do you? isn't it? etc.)",

  53: "Verb + -ing (enjoy doing / stop doing etc.)",
  54: "Verb + to ... (decide to ... / forget to ... etc.)",
  55: "Verb (+ object) + to ... (I want you to ...)",
  56: "Verb + -ing or to ... 1 (remember, regret etc.)",
  57: "Verb + -ing or to ... 2 (try, need, help)",
  58: "Verb + -ing or to ... 3 (like / would like etc.)",
  59: "prefer and would rather",
  60: "Preposition + -ing (in/for/about etc.)",
  61: "be/get used to ... (I'm used to ...)",
  62: "Verb + preposition + -ing (succeed in -ing / insist on -ing etc.)",
  63: "there's no point in -ing / it's worth -ing etc.",
  64: "to ... , for ... and so that ...",
  65: "Adjective + to ...",
  66: "to ... (afraid to do) and preposition + -ing (afraid of -ing)",
  67: "see somebody do and see somebody doing",
  68: "-ing clauses (He hurt his knee playing football.)",

  69: "Countable and uncountable 1",
  70: "Countable and uncountable 2",
  71: "Countable nouns with a/an and some",
  72: "a/an and the",
  73: "the 1",
  74: "the 2 (school / the school etc.)",
  75: "the 3 (children / the children)",
  76: "the 4 (the giraffe / the telephone / the old etc.)",
  77: "Names with and without the 1",
  78: "Names with and without the 2",
  79: "Singular and plural",
  80: "Noun + noun (a bus driver / a headache)",
  81: "-'s (your sister's name) and of ... (the name of the book)",

  82: "myself/yourself/themselves etc.",
  83: "a friend of mine / my own house / on my own / by myself",
  84: "there ... and it ...",
  85: "some and any",
  86: "no/none/any / nothing/nobody etc.",
  87: "much, many, little, few, a lot, plenty",
  88: "all / all of / most / most of / no / none of etc.",
  89: "both / both of / neither / neither of / either / either of",
  90: "all / every / whole",
  91: "each and every",

  92: "Relative clauses 1: clauses with who/that/which",
  93: "Relative clauses 2: clauses with and without who/that/which",
  94: "Relative clauses 3: whose/whom/where",
  95: "Relative clauses 4: extra information clauses (1)",
  96: "Relative clauses 5: extra information clauses (2)",
  97: "-ing and -ed clauses (the woman talking to Tom, the boy injured in the accident)",

  98: "Adjectives ending in -ing and -ed (boring/bored etc.)",
  99: "Adjectives: a nice new house / you look tired",
  100: "Adjectives and adverbs 1 (quick/quickly)",
  101: "Adjectives and adverbs 2 (well, fast, late, hard/hardly)",
  102: "so and such",
  103: "enough and too",
  104: "quite, pretty, rather and fairly",
  105: "Comparative 1 (cheaper, more expensive etc.)",
  106: "Comparative 2 (much better / any better etc.)",
  107: "Comparative 3 (as ... as / than)",
  108: "Superlative (the longest, the most enjoyable etc.)",
  109: "Word order 1: verb + object; place and time",
  110: "Word order 2: adverbs with the verb",
  111: "still / any more / yet / already",
  112: "even",

  113: "although / though / even though / in spite of / despite",
  114: "in case",
  115: "unless / as long as / provided",
  116: "as (as I walked ... / as I was ... etc.)",
  117: "like and as",
  118: "like / as if",
  119: "during / for / while",
  120: "by and until / by the time ...",

  121: "at/on/in (time)",
  122: "on time and in time / at the end and in the end",
  123: "in/at/on (position) 1",
  124: "in/at/on (position) 2",
  125: "in/at/on (position) 3",
  126: "to / at / in / into",
  127: "in/on/at (other uses)",
  128: "by",
  129: "Noun + preposition (reason for, cause of etc.)",
  130: "Adjective + preposition 1",
  131: "Adjective + preposition 2",
  132: "Verb + preposition 1 (to and at)",
  133: "Verb + preposition 2 (about/for/of/after)",
  134: "Verb + preposition 3 (about and of)",
  135: "Verb + preposition 4 (of/for/from/on)",
  136: "Verb + preposition 5 (in/into/with/to/on)",

  137: "Phrasal verbs 1 Introduction",
  138: "Phrasal verbs 2 in/out",
  139: "Phrasal verbs 3 out",
  140: "Phrasal verbs 4 on/off (1)",
  141: "Phrasal verbs 5 on/off (2)",
  142: "Phrasal verbs 6 up/down",
  143: "Phrasal verbs 7 up (1)",
  144: "Phrasal verbs 8 up (2)",
  145: "Phrasal verbs 9 away/back",
};

// 2. ESTRUCTURA DE LES ACTIVITATS (Basat en Cambridge Intermediate)
const dadesApp = {
  issues: [
    {
      titol: "Present and past",
      preguntes: [
        {
          id: "1.1",
          text_pre: "At first I didn’t like my job, but",
          text_post: "to enjoy it now.",
          opcions: ["A I’m starting", "B I start"],
          solucions: ["A"],
          unitats: [1, 3],
        },
        {
          id: "1.2",
          text_pre: "I don’t understand this sentence. What",
          text_post: "?",
          opcions: [
            "A does mean this word",
            "B does this word mean",
            "C means this Word",
          ],
          solucions: ["B"],
          unitats: [2, 49],
        },
        {
          id: "1.3",
          text_pre: "Robert",
          text_post: "away two or three times a year.",
          opcions: [
            "A is going usually",
            "B is usually going",
            "C usually goes",
            "D goes usually",
          ],
          solucions: ["C"],
          unitats: [2, 3, 110],
        },
        {
          id: "1.4",
          text_pre: "How",
          text_post: "now? Better than before?",
          opcions: ["A you are feeling", "B do you feel", "C are you feeling"],
          solucions: ["B", "C"],
          unitats: [4],
        },
        {
          id: "1.5",
          text_pre: "It was a boring weekend.",
          text_post: "anything.",
          opcions: ["A I didn’t", "B I don’t do", "C I didn’t do"],
          solucions: ["C"],
          unitats: [5],
        },
        {
          id: "1.6",
          text_pre: "Matt",
          text_post: "while we were having dinner.",
          opcions: ["A phoned", "B was phoning", "C has phoned"],
          solucions: ["A"],
          unitats: [6, 14],
        },
      ],
    },
    {
      titol: "Present perfect and past",
      preguntes: [
        {
          id: "2.1",
          text_pre: "James is on holiday. He",
          text_post: "to Italy.",
          opcions: ["A is gone", "B has gone", "C has been"],
          solucions: ["B"],
          unitats: [7],
        },
        {
          id: "2.2",
          text_pre: "Everything is going well. There",
          text_post: "any problems so far.",
          opcions: ["A weren’t", "B have been", "C haven’t been"],
          solucions: ["C"],
          unitats: [8],
        },
        {
          id: "2.3",
          text_pre:
            "Sarah has lost her passport again. This is the second time this",
          text_post: ".",
          opcions: [
            "A has happened",
            "B happens",
            "C happened",
            "D is happening",
          ],
          solucions: ["A"],
          unitats: [8],
        },
        {
          id: "2.4",
          text_pre: "Why are you out of breath?",
          text_post: "?",
          opcions: [
            "A Are you running",
            "B Have you run",
            "C Have you been running",
          ],
          solucions: ["C"],
          unitats: [9],
        },
        {
          id: "2.5",
          text_pre: "Where’s the book I gave you? What",
          text_post: "with it?",
          opcions: [
            "A have you done",
            "B have you been doing",
            "C are you doing",
          ],
          solucions: ["A"],
          unitats: [10],
        },
        {
          id: "2.6",
          text_pre: "‘How long",
          text_post: "Jane?’ ‘A long time. Since we were at school.’",
          opcions: [
            "A do you know",
            "B have you known",
            "C have you been knowing",
          ],
          solucions: ["B"],
          unitats: [11, 10],
        },
        {
          id: "2.7",
          text_pre: "Sally has been working here",
          text_post: ".",
          opcions: [
            "A for six months",
            "B since six months",
            "C six months ago",
            "D six months",
          ],
          solucions: ["A", "D"],
          unitats: [12],
        },
        {
          id: "2.8",
          text_pre: "It’s two years",
          text_post: "Joe.",
          opcions: [
            "A that I don’t see",
            "B that I haven’t seen",
            "C since I didn’t see",
            "D since I last saw",
          ],
          solucions: ["D"],
          unitats: [12],
        },
        {
          id: "2.9",
          text_pre: "It",
          text_post: "raining for a while, but now it’s raining again.",
          opcions: ["A stopped", "B has stopped", "C was stopped"],
          solucions: ["A"],
          unitats: [13],
        },
        {
          id: "2.10",
          text_pre: "My mother",
          text_post: "in Italy.",
          opcions: ["A grew up", "B has grown up", "C had grown up"],
          solucions: ["A"],
          unitats: [13],
        },
        {
          id: "2.11",
          text_pre: "",
          text_post: "a lot of sweets when you were a child?",
          opcions: ["A Have you eaten", "B Had you eaten", "C Did you eat"],
          solucions: ["C"],
          unitats: [14],
        },
        {
          id: "2.12",
          text_pre: "Jack",
          text_post: "in New York for ten years. Now he lives in Los Angeles.",
          opcions: ["A lived", "B has lived", "C has been living"],
          solucions: ["A"],
          unitats: [14, 11],
        },
        {
          id: "2.13",
          text_pre: "The people sitting next to me on the plane were nervous.",
          text_post: "before.",
          opcions: [
            "A They haven’t flown",
            "B They didn’t fly",
            "C They hadn’t flown",
            "D They’d never flown",
            "E They weren’t flying",
          ],
          solucions: ["C", "D"],
          unitats: [15],
        },
        {
          id: "2.14",
          text_pre: "Katherine was lying on the sofa. She was tired because",
          text_post: "very hard.",
          opcions: [
            "A she was working",
            "B she’s been working",
            "C she’d been working",
          ],
          solucions: ["C"],
          unitats: [16],
        },
        {
          id: "2.15",
          text_pre: "",
          text_post: "a car when you were living in Paris?",
          opcions: [
            "A Had you",
            "B Were you having",
            "C Have you had",
            "D Did you have",
          ],
          solucions: ["D"],
          unitats: [17, 14],
        },
        {
          id: "2.16",
          text_pre: "I",
          text_post: "tennis a lot, but I don’t play very much now.",
          opcions: ["A was playing", "B was used to play", "C used to play"],
          solucions: ["C"],
          unitats: [18],
        },
      ],
    },

    {
      titol: "Future",
      preguntes: [
        {
          id: "3.1",
          text_pre: "I’m tired.",
          text_post: "to bed now. Goodnight.",
          opcions: ["A I go", "B I’m going"],
          solucions: ["B"],
          unitats: [19],
        },
        {
          id: "3.2",
          text_pre: "",
          text_post: "tomorrow, so we can go out somewhere.",
          opcions: ["A I’m not working", "B I don’t work", "C I won’t work"],
          solucions: ["A"],
          unitats: [19, 21],
        },
        {
          id: "3.3",
          text_pre: "That bag looks heavy.",
          text_post: "you with it.",
          opcions: ["A I’m helping", "B I help", "C I’ll help"],
          solucions: ["C"],
          unitats: [21],
        },
        {
          id: "3.4",
          text_pre: "I think the weather",
          text_post: "nice later.",
          opcions: ["A will be", "B is", "C is going to be", "D shall be"],
          solucions: ["A", "C"],
          unitats: [23, 22],
        },
        {
          id: "3.5",
          text_pre: "‘Anna is in hospital.’ ‘Yes, I know.",
          text_post: "her this evening.’",
          opcions: ["A I visit", "B I’m going to visit", "C I’ll visit"],
          solucions: ["B"],
          unitats: [23, 20],
        },
        {
          id: "3.6",
          text_pre: "We’re late. The film",
          text_post: "by the time we get to the cinema.",
          opcions: [
            "A will already start",
            "B will be already started",
            "C will already have started",
          ],
          solucions: ["C"],
          unitats: [24],
        },
        {
          id: "3.7",
          text_pre: "Don’t worry",
          text_post: "late tonight.",
          opcions: ["A if I’m", "B when I’m", "C when I’ll be", "D if I’ll be"],
          solucions: ["A"],
          unitats: [25],
        },
      ],
    },

    {
      titol: "Modals",
      preguntes: [
        {
          id: "4.1",
          text_pre: "The fire spread quickly, but everybody",
          text_post: "from the building.",
          opcions: [
            "A was able to escape",
            "B managed to escape",
            "C could escape",
          ],
          solucions: ["A", "B"],
          unitats: [26],
        },
        {
          id: "4.2",
          text_pre: "I’m so tired I",
          text_post: "for a week.",
          opcions: ["A can sleep", "B could sleep", "C could have slept"],
          solucions: ["B"],
          unitats: [27],
        },
        {
          id: "4.3",
          text_pre: "The story",
          text_post: "be true, but I don’t think it is.",
          opcions: ["A might", "B can", "C could", "D may"],
          solucions: ["A", "C", "D"],
          unitats: [27, 29],
        },
        {
          id: "4.4",
          text_pre: "Why did you stay at a hotel? You",
          text_post: "with me.",
          opcions: ["A can stay", "B could stay", "C could have stayed"],
          solucions: ["C"],
          unitats: [27],
        },
        {
          id: "4.5",
          text_pre: "I lost one of my gloves. I",
          text_post: "it somewhere.",
          opcions: [
            "A must drop",
            "B must have dropped",
            "C must be dropping",
            "D must have been dropping",
          ],
          solucions: ["B"],
          unitats: [28],
        },
        {
          id: "4.6",
          text_pre: "‘Why wasn’t Amy at the meeting yesterday?’ ‘She",
          text_post: "about it.’",
          opcions: [
            "A might not know",
            "B may not know",
            "C might not have known",
            "D may not have known",
          ],
          solucions: ["C", "D"],
          unitats: [29],
        },
        {
          id: "4.7",
          text_pre: "What",
          text_post: "to get a new driving licence?",
          opcions: [
            "A have I to do",
            "B do I have to do",
            "C I must do",
            "D I have to",
          ],
          solucions: ["B"],
          unitats: [31],
        },
        {
          id: "4.8",
          text_pre: "We have plenty of time. We",
          text_post: "hurry.",
          opcions: ["A don’t need to", "B mustn’t", "C needn’t"],
          solucions: ["A", "C"],
          unitats: [32],
        },
        {
          id: "4.9",
          text_pre: "You missed a great party last night. You",
          text_post: ". Why didn’t you?",
          opcions: [
            "A must have come",
            "B should have come",
            "C ought to have come",
            "D had to come",
          ],
          solucions: ["B", "C"],
          unitats: [33],
        },
        {
          id: "4.10",
          text_pre: "Jane won the lottery. I suggested",
          text_post: "a car with the money she won.",
          opcions: [
            "A that she buy",
            "B that she should buy",
            "C her to buy",
            "D that she bought",
          ],
          solucions: ["A", "B", "D"],
          unitats: [34],
        },
        {
          id: "4.11",
          text_pre: "You’re always at home. You",
          text_post: "out more often.",
          opcions: ["A should go", "B had better go", "C had better to go"],
          solucions: ["A"],
          unitats: [35],
        },
        {
          id: "4.12",
          text_pre: "It’s late. It’s time",
          text_post: "home.",
          opcions: [
            "A we go",
            "B we must go",
            "C we should go",
            "D we went",
            "E to go",
          ],
          solucions: ["D", "E"],
          unitats: [35],
        },
        {
          id: "4.13",
          text_pre: "",
          text_post: "a little longer, but I really have to go now.",
          opcions: [
            "A I’d stay",
            "B I’ll stay",
            "C I can stay",
            "D I’d have stayed",
          ],
          solucions: ["A"],
          unitats: [36],
        },
      ],
    },

    {
      titol: "If and wish",
      preguntes: [
        {
          id: "5.1",
          text_pre: "I’m not tired enough to go to bed. If I",
          text_post: "to bed now, I wouldn’t sleep.",
          opcions: ["A go", "B went", "C had gone", "D would go"],
          solucions: ["B"],
          unitats: [38, 39],
        },
        {
          id: "5.2",
          text_pre: "If I were rich,",
          text_post: "a lot.",
          opcions: [
            "A I’ll travel",
            "B I can travel",
            "C I would travel",
            "D I travelled",
          ],
          solucions: ["C"],
          unitats: [39],
        },
        {
          id: "5.3",
          text_pre: "I wish I",
          text_post: "have to work tomorrow, but unfortunately I do.",
          opcions: ["A don’t", "B didn’t", "C wouldn’t", "D won’t"],
          solucions: ["B"],
          unitats: [39, 41],
        },
        {
          id: "5.4",
          text_pre:
            "The view was wonderful. I would have taken some pictures if",
          text_post: "a camera with me.",
          opcions: [
            "A I had",
            "B I would have",
            "C I would have had",
            "D I’d had",
          ],
          solucions: ["D"],
          unitats: [40],
        },
        {
          id: "5.5",
          text_pre: "The weather is horrible. I wish it",
          text_post: "raining.",
          opcions: ["A would stop", "B stopped", "C stops", "D will stop"],
          solucions: ["A"],
          unitats: [41],
        },
      ],
    },

    {
      titol: "Passive",
      preguntes: [
        {
          id: "6.1",
          text_pre: "We",
          text_post: "by a loud noise during the night.",
          opcions: [
            "A woke up",
            "B are woken up",
            "C were woken up",
            "D were waking up",
          ],
          solucions: ["C"],
          unitats: [42],
        },
        {
          id: "6.2",
          text_pre: "A new supermarket is going to",
          text_post: "next year.",
          opcions: ["A build", "B be built", "C be building", "D building"],
          solucions: ["B"],
          unitats: [43],
        },
        {
          id: "6.3",
          text_pre: "There’s somebody walking behind us. I think",
          text_post: ".",
          opcions: [
            "A we are following",
            "B we are being following",
            "C we are followed",
            "D we are being followed",
          ],
          solucions: ["D"],
          unitats: [43],
        },
        {
          id: "6.4",
          text_pre: "‘Where",
          text_post: "?’ ‘In Chicago.’",
          opcions: [
            "A were you born",
            "B are you born",
            "C have you been born",
            "D did you born",
          ],
          solucions: ["A"],
          unitats: [44],
        },
        {
          id: "6.5",
          text_pre: "There was a fight, but nobody",
          text_post: ".",
          opcions: ["A was hurt", "B got hurt", "C hurt"],
          solucions: ["A", "B"],
          unitats: [44],
        },
        {
          id: "6.6",
          text_pre: "Jane",
          text_post: "to phone me last night, but she didn’t.",
          opcions: ["A supposed", "B is supposed", "C was supposed"],
          solucions: ["C"],
          unitats: [45],
        },
        {
          id: "6.7",
          text_pre: "Where",
          text_post: "? Which hairdresser did you go to?",
          opcions: [
            "A did you cut your hair",
            "B have you cut your hair",
            "C did you have cut your hair",
            "D did you have your hair cut",
          ],
          solucions: ["D"],
          unitats: [46],
        },
      ],
    },

    {
      titol: "Reported speech",
      preguntes: [
        {
          id: "7.1",
          text_pre: "Paul left the room suddenly. He said he",
          text_post: "to go.",
          opcions: ["A had", "B has", "C have"],
          solucions: ["A"],
          unitats: [48, 47],
        },
        {
          id: "7.2",
          text_pre:
            "(You meet Joe in the street.) Joe, this is a surprise. Rachel said you",
          text_post: "in hospital.",
          opcions: ["A are", "B were", "C was"],
          solucions: ["B"],
          unitats: [48, 47],
        },
        {
          id: "7.3",
          text_pre: "Anna",
          text_post: "and left.",
          opcions: [
            "A said goodbye to me",
            "B said me goodbye",
            "C told me goodbye",
          ],
          solucions: ["A"],
          unitats: [48],
        },
      ],
    },
    {
      titol: "Questions and auxiliary verbs",
      preguntes: [
        {
          id: "8.1",
          text_pre: "‘What time",
          text_post: "?’ ‘At 8.30.’",
          opcions: [
            "A starts the film",
            "B does start the film",
            "C does the film start",
          ],
          solucions: ["C"],
          unitats: [49],
        },
        {
          id: "8.2",
          text_pre: "‘Do you know where",
          text_post: "?’ ‘No, he didn’t say.’",
          opcions: ["A Tom has gone", "B has Tom gone", "C has gone Tom"],
          solucions: ["A"],
          unitats: [50],
        },
        {
          id: "8.3",
          text_pre: "The police officer stopped us and asked us where",
          text_post: ".",
          opcions: [
            "A were we going",
            "B are we going",
            "C we are going",
            "D we were going",
          ],
          solucions: ["D"],
          unitats: [50],
        },
        {
          id: "8.4",
          text_pre: "‘Do you think it will rain?’ ‘",
          text_post: ".’",
          opcions: ["A I hope not", "B I don’t hope", "C I don’t hope so"],
          solucions: ["A"],
          unitats: [51],
        },
        {
          id: "8.5",
          text_pre: "‘You don’t know where Karen is,",
          text_post: "?’ ‘Sorry, I have no idea.’",
          opcions: ["A don’t you", "B do you", "C is she", "D are you"],
          solucions: ["B"],
          unitats: [52],
        },
      ],
    },

    {
      titol: "Ing and to ...",
      preguntes: [
        {
          id: "9.1",
          text_pre: "You can’t stop people",
          text_post: "what they want.",
          opcions: ["A doing", "B do", "C to do", "D from doing"],
          solucions: ["A", "D"],
          unitats: [56, 62],
        },
        {
          id: "9.2",
          text_pre: "I’d better go now. I promised",
          text_post: "late.",
          opcions: [
            "A not being",
            "B not to be",
            "C to not be",
            "D I wouldn’t be",
          ],
          solucions: ["A", "D"],
          unitats: [54, 56],
        },
        {
          id: "9.3",
          text_pre: "Do you want",
          text_post: "with you or do you want to go alone?",
          opcions: [
            "A me coming",
            "B me to come",
            "C that I come",
            "D that I will come",
          ],
          solucions: ["B"],
          unitats: [55],
        },
        {
          id: "9.4",
          text_pre: "I know I locked the door. I clearly remember",
          text_post: "it.",
          opcions: ["A locking", "B to lock", "C to have locked"],
          solucions: ["A"],
          unitats: [56],
        },
        {
          id: "9.5",
          text_pre: "She tried to be serious, but she couldn’t help",
          text_post: ".",
          opcions: [
            "A laughing",
            "B to laugh",
            "C that she laughed",
            "D laugh",
          ],
          solucions: ["A"],
          unitats: [57],
        },
        {
          id: "9.6",
          text_pre: "Paul lives in Berlin now. He likes",
          text_post: "there.",
          opcions: ["A living", "B to live"],
          solucions: ["A"],
          unitats: [58],
        },
        {
          id: "9.7",
          text_pre: "It’s not my favourite job, but I like",
          text_post: "the kitchen as often as possible.",
          opcions: ["A cleaning", "B clean", "C to clean", "D that I clean"],
          solucions: ["C"],
          unitats: [58],
        },
        {
          id: "9.8",
          text_pre: "I’m tired. I’d rather",
          text_post: "out this evening, if you don’t mind.",
          opcions: ["A not going", "B not to go", "C don’t go", "D not go"],
          solucions: ["D"],
          unitats: [59],
        },
        {
          id: "9.9",
          text_pre: "I’d rather",
          text_post: "anyone what I said.",
          opcions: [
            "A you don’t tell",
            "B not you tell",
            "C you didn’t tell",
            "D you wouldn’t tell",
          ],
          solucions: ["C"],
          unitats: [59],
        },
        {
          id: "9.10",
          text_pre: "Are you looking forward",
          text_post: "on holiday?",
          opcions: ["A going", "B to go", "C to going", "D that you go"],
          solucions: ["C"],
          unitats: [60, 62],
        },
        {
          id: "9.11",
          text_pre: "When Lisa first came to Britain, she wasn’t used",
          text_post: "on the left.",
          opcions: ["A driving", "B to driving", "C to drive", "D drive"],
          solucions: ["B"],
          unitats: [61],
        },
        {
          id: "9.12",
          text_pre: "I’m thinking",
          text_post: "a house. Do you think that’s a good idea?",
          opcions: ["A to buy", "B of to buy", "C of buying", "D about buying"],
          solucions: ["C", "D"],
          unitats: [62, 66],
        },
        {
          id: "9.13",
          text_pre: "I had no trouble",
          text_post: "a place to stay. In fact it was surprisingly easy.",
          opcions: ["A find", "B found", "C to find", "D finding"],
          solucions: ["D"],
          unitats: [63],
        },
        {
          id: "9.14",
          text_pre: "I called the restaurant",
          text_post: "a table.",
          opcions: [
            "A for reserve",
            "B to reserve",
            "C for reserving",
            "D for to reserve",
          ],
          solucions: ["B"],
          unitats: [64],
        },
        {
          id: "9.15",
          text_pre: "James doesn’t speak clearly.",
          text_post: ".",
          opcions: [
            "A It is hard to understand him",
            "B He is hard to understand",
            "C He is hard to understand him",
          ],
          solucions: ["A", "B"],
          unitats: [65],
        },
        {
          id: "9.16",
          text_pre:
            "The path was icy, so we walked very carefully. We were afraid",
          text_post: "",
          opcions: [
            "A of falling",
            "B from falling",
            "C to fall",
            "D to falling",
          ],
          solucions: ["A"],
          unitats: [66],
        },
        {
          id: "9.17",
          text_pre: "I didn’t hear you",
          text_post: "in. You must have been very quiet.",
          opcions: ["A come", "B to come", "C came"],
          solucions: ["A"],
          unitats: [67],
        },
        {
          id: "9.18",
          text_pre: "",
          text_post: "a hotel, we looked for somewhere to eat.",
          opcions: [
            "A Finding",
            "B After finding",
            "C Having found",
            "D We found",
          ],
          solucions: ["B", "C"],
          unitats: [68],
        },
      ],
    },

    {
      titol: "Articles and nouns",
      preguntes: [
        {
          id: "10.1",
          text_pre: "It wasn’t your fault. It was",
          text_post: ".",
          opcions: ["A accident", "B an accident", "C some accident"],
          solucions: ["B"],
          unitats: [69],
        },
        {
          id: "10.2",
          text_pre: "Where are you going to put all your",
          text_post: "?",
          opcions: ["A furniture", "B furnitures"],
          solucions: ["A"],
          unitats: [70],
        },
        {
          id: "10.3",
          text_pre: "‘Where are you going?’ ‘I’m going to buy",
          text_post: ".’",
          opcions: ["A a bread", "B some bread", "C a loaf of bread"],
          solucions: ["B", "C"],
          unitats: [70],
        },
        {
          id: "10.4",
          text_pre: "Sandra is",
          text_post: ". She works at a large hospital.",
          opcions: ["A nurse", "B a nurse", "C the nurse"],
          solucions: ["B"],
          unitats: [71, 72],
        },
        {
          id: "10.5",
          text_pre: "Helen works six days",
          text_post: "week.",
          opcions: ["A in", "B for", "C a", "D the"],
          solucions: ["C"],
          unitats: [72],
        },
        {
          id: "10.6",
          text_pre: "There are millions of stars in",
          text_post: ".",
          opcions: ["A space", "B a space", "C the space"],
          solucions: ["A"],
          unitats: [73],
        },
        {
          id: "10.7",
          text_pre: "Every day",
          text_post: "starts at 9 and finishes at 3.",
          opcions: ["A school", "B a school", "C the school"],
          solucions: ["A"],
          unitats: [74],
        },
        {
          id: "10.8",
          text_pre: "",
          text_post: "changed a lot in the last thirty years.",
          opcions: ["A Life has", "B The life has", "C The lives have"],
          solucions: ["A"],
          unitats: [75],
        },
        {
          id: "10.9",
          text_pre: "When",
          text_post: "invented?",
          opcions: [
            "A was camera",
            "B were cameras",
            "C were the cameras",
            "D was the camera",
          ],
          solucions: ["D"],
          unitats: [76],
        },
        {
          id: "10.10",
          text_pre: "Have you been to",
          text_post: "?",
          opcions: [
            "A Canada or United States",
            "B the Canada or the United States",
            "C Canada or the United States",
            "D the Canada or United States",
          ],
          solucions: ["C"],
          unitats: [77],
        },
        {
          id: "10.11",
          text_pre: "On our first day in Moscow, we visited",
          text_post: ".",
          opcions: ["A Kremlin", "B a Kremlin", "C the Kremlin"],
          solucions: ["C"],
          unitats: [78],
        },
        {
          id: "10.12",
          text_pre: "I have some news for you.",
          text_post: ".",
          opcions: [
            "A It’s good news",
            "B They are good news",
            "C It’s a good news",
          ],
          solucions: ["A"],
          unitats: [79, 70],
        },
        {
          id: "10.13",
          text_pre: "It took us quite a long time to get here. It was",
          text_post: "journey.",
          opcions: ["A three hour", "B a three-hours", "C a three-hour"],
          solucions: ["C"],
          unitats: [80],
        },
        {
          id: "10.14",
          text_pre: "This isn’t my book. It’s",
          text_post: ".",
          opcions: [
            "A my sister",
            "B my sister’s",
            "C from my sister",
            "D of my sister",
            "E of my sister’s",
          ],
          solucions: ["B"],
          unitats: [81],
        },
      ],
    },

    {
      titol: "Pronouns and determiners",
      preguntes: [
        {
          id: "11.1",
          text_pre: "What time shall we",
          text_post: "tomorrow?",
          opcions: ["A meet", "B meet us", "C meet ourselves"],
          solucions: ["A"],
          unitats: [82],
        },
        {
          id: "11.2",
          text_pre: "I’m going to a wedding on Saturday.",
          text_post: "is getting married.",
          opcions: [
            "A A friend of me",
            "B A friend of mine",
            "C One my Friends",
          ],
          solucions: ["B"],
          unitats: [83],
        },
        {
          id: "11.3",
          text_pre: "They live on a busy road.",
          text_post: "a lot of noise from the traffic.",
          opcions: [
            "A It must be",
            "B It must have",
            "C There must have",
            "D There must be",
          ],
          solucions: ["D"],
          unitats: [84],
        },
        {
          id: "11.4",
          text_pre: "He’s lazy. He never does",
          text_post: "work.",
          opcions: ["A some", "B any", "C no"],
          solucions: ["B"],
          unitats: [85],
        },
        {
          id: "11.5",
          text_pre: "‘What would you like to eat?’ ‘I don’t mind.",
          text_post: "– whatever you have.’",
          opcions: ["A Something", "B Anything", "C Nothing"],
          solucions: ["B"],
          unitats: [85],
        },
        {
          id: "11.6",
          text_pre: "The course didn’t go well.",
          text_post: "of the students were happy.",
          opcions: ["A All", "B No-one", "C None", "D Nobody"],
          solucions: ["C"],
          unitats: [86],
        },
        {
          id: "11.7",
          text_pre: "We went shopping and spent",
          text_post: "money.",
          opcions: ["A a lot of", "B much", "C lots of", "D many"],
          solucions: ["A", "C"],
          unitats: [87],
        },
        {
          id: "11.8",
          text_pre: "I was ill yesterday. I spent",
          text_post: "in bed.",
          opcions: [
            "A the most of day",
            "B most of day",
            "C the most of the day",
            "D most of the day",
          ],
          solucions: ["D"],
          unitats: [88],
        },
        {
          id: "11.9",
          text_pre: "I asked two people how to get to the station, but",
          text_post: "of them knew.",
          opcions: ["A none", "B either", "C both", "D neither"],
          solucions: ["D"],
          unitats: [89],
        },
        {
          id: "11.10",
          text_pre: "Our holiday was a disaster.",
          text_post: "went wrong.",
          opcions: ["A Everything", "B All", "C All things", "D All of things"],
          solucions: ["A"],
          unitats: [90],
        },
        {
          id: "11.11",
          text_pre: "The bus service is excellent. There’s a bus",
          text_post: "ten minutes.",
          opcions: ["A each", "B every", "C all"],
          solucions: ["B"],
          unitats: [90, 91],
        },
        {
          id: "11.12",
          text_pre: "There were four books on the table.",
          text_post: "a different colour.",
          opcions: [
            "A Each of books was",
            "B Each of the books was",
            "C Each book was",
          ],
          solucions: ["B", "C"],
          unitats: [91],
        },
      ],
    },

    {
      titol: "Relative clauses",
      preguntes: [
        {
          id: "12.1",
          text_pre: "I don’t like stories",
          text_post: "have unhappy endings.",
          opcions: ["A that", "B they", "C which", "D who"],
          solucions: ["A", "C"],
          unitats: [92],
        },
        {
          id: "12.2",
          text_pre: "I didn’t believe them at first, but in fact everything",
          text_post: "was true.",
          opcions: ["A they said", "B that they said", "C what they said"],
          solucions: ["A", "B"],
          unitats: [93],
        },
        {
          id: "12.3",
          text_pre: "We helped some people",
          text_post: ".",
          opcions: [
            "A their car had broken down",
            "B which car had broken down",
            "C whose car had broken down",
            "D that their car had broken down",
          ],
          solucions: ["C"],
          unitats: [94],
        },
        {
          id: "12.4",
          text_pre: "Anna told me about her new job,",
          text_post: "a lot.",
          opcions: [
            "A that she’s enjoying",
            "B which she’s enjoying",
            "C she’s enjoying",
            "D she’s enjoying it",
          ],
          solucions: ["B"],
          unitats: [95],
        },
        {
          id: "12.5",
          text_pre: "Sarah couldn’t meet us,",
          text_post: "was a shame.",
          opcions: ["A that", "B it", "C what", "D which"],
          solucions: ["D"],
          unitats: [96],
        },
        {
          id: "12.6",
          text_pre: "George showed me some pictures",
          text_post: "by his father.",
          opcions: [
            "A painting",
            "B painted",
            "C that were painted",
            "D they were painted",
          ],
          solucions: ["B", "C"],
          unitats: [97, 92],
        },
      ],
    },

    {
      titol: "Adjectives and adverbs",
      preguntes: [
        {
          id: "13.1",
          text_pre: "Jane doesn’t enjoy her job any more. She’s",
          text_post: "because every day she does exactly the same thing.",
          opcions: ["A boring", "B bored"],
          solucions: ["B"],
          unitats: [98],
        },
        {
          id: "13.2",
          text_pre: "Lisa was carrying a",
          text_post: "bag.",
          opcions: [
            "A black small plastic",
            "B small and black plastic",
            "C small black plastic",
            "D plastic small black",
          ],
          solucions: ["C"],
          unitats: [99],
        },
        {
          id: "13.3",
          text_pre: "Maria’s English is excellent. She speaks",
          text_post: ".",
          opcions: [
            "A perfectly English",
            "B English perfectly",
            "C perfect English",
            "D English perfect",
          ],
          solucions: ["B", "C"],
          unitats: [100],
        },
        {
          id: "13.4",
          text_pre: "He",
          text_post: "to find a job, but he had no luck.",
          opcions: ["A tried hard", "B tried hardly", "C hardly tried"],
          solucions: ["A"],
          unitats: [101],
        },
        {
          id: "13.5",
          text_pre: "I haven’t seen her for",
          text_post: ", I’ve forgotten what she looks like.",
          opcions: [
            "A so long",
            "B so long time",
            "C a such long time",
            "D such a long time",
          ],
          solucions: ["A", "D"],
          unitats: [102],
        },
        {
          id: "13.6",
          text_pre: "Don’t stand on that chair. It isn’t",
          text_post: ".",
          opcions: [
            "A enough strong to stand on",
            "B strong enough to stand on it",
            "C strong enough to stand on",
            "D strong enough for stand on",
          ],
          solucions: ["C"],
          unitats: [103],
        },
        {
          id: "13.7",
          text_pre: "Sarah is doing OK at the moment. She has",
          text_post: ".",
          opcions: [
            "A a quite good job",
            "B quite a good job",
            "C a pretty good job",
          ],
          solucions: ["B", "C"],
          unitats: [104],
        },
        {
          id: "13.8",
          text_pre: "The exam was quite easy –",
          text_post: "I expected.",
          opcions: [
            "A more easy that",
            "B more easy than",
            "C easier than",
            "D easier as",
          ],
          solucions: ["C"],
          unitats: [105],
        },
        {
          id: "13.9",
          text_pre: "The more expensive the hotel,",
          text_post: ".",
          opcions: [
            "A the service will be better",
            "B will be better the service",
            "C the better the service",
            "D better the service will be",
          ],
          solucions: ["C"],
          unitats: [106],
        },
        {
          id: "13.10",
          text_pre: "Patrick is a fast runner. I can’t run as fast as",
          text_post: ".",
          opcions: ["A he", "B him", "C he can"],
          solucions: ["B", "C"],
          unitats: [107],
        },
        {
          id: "13.11",
          text_pre: "What’s",
          text_post: "you’ve ever made?",
          opcions: [
            "A most important decision",
            "B the more important decisión",
            "C the decision more important",
            "D the most important decisión",
          ],
          solucions: ["D"],
          unitats: [108],
        },
        {
          id: "13.12",
          text_pre: "Ben likes walking.",
          text_post: ".",
          opcions: [
            "A Every morning he walks to work",
            "B He walks to work every morning",
            "C He walks every morning to work",
            "D He every morning walks to work",
          ],
          solucions: ["A", "B"],
          unitats: [109],
        },
        {
          id: "13.13",
          text_pre: "Joe never phones me.",
          text_post: ".",
          opcions: [
            "A Always I have to phone him",
            "B I always have to phone him",
            "C I have always to phone him",
            "D I have to phone always him",
          ],
          solucions: ["B"],
          unitats: [110],
        },
        {
          id: "13.14",
          text_pre: "Lucy",
          text_post: ". She left last month.",
          opcions: [
            "A still doesn’t work here",
            "B doesn’t still work here",
            "C no more works here",
            "D doesn’t work here any more",
            "E no longer works here",
          ],
          solucions: ["D", "E"],
          unitats: [111],
        },
        {
          id: "13.15",
          text_pre: "",
          text_post: "she can’t drive, she has a car.",
          opcions: ["A Even", "B Even when", "C Even if", "D Even though"],
          solucions: ["D"],
          unitats: [112, 113],
        },
      ],
    },

    {
      titol: "Conjunctions and prepositions",
      preguntes: [
        {
          id: "14.1",
          text_pre: "I couldn’t sleep",
          text_post: "very tired.",
          opcions: [
            "A although I was",
            "B despite I was",
            "C despite of being",
            "D in spite of being",
          ],
          solucions: ["A", "D"],
          unitats: [113],
        },
        {
          id: "14.2",
          text_pre: "You should insure your bike",
          text_post: "stolen.",
          opcions: [
            "A in case it will be",
            "B if it will be",
            "C in case it is",
            "D if it is",
          ],
          solucions: ["C"],
          unitats: [114],
        },
        {
          id: "14.3",
          text_pre: "The club is for members only. You",
          text_post: "you’re a member.",
          opcions: [
            "A can’t go in if",
            "B can go in only if",
            "C can’t go in unless",
            "D can go in unless",
          ],
          solucions: ["B", "C"],
          unitats: [115],
        },
        {
          id: "14.4",
          text_pre: "Yesterday we watched TV all evening",
          text_post: "we didn’t have anything better to do.",
          opcions: ["A when", "B as", "C while", "D since"],
          solucions: ["B", "D"],
          unitats: [116],
        },
        {
          id: "14.5",
          text_pre: "‘What’s that noise?’ ‘It sounds",
          text_post: "a baby crying.’",
          opcions: ["A as", "B like", "C as if", "D as though"],
          solucions: ["B"],
          unitats: [117, 118],
        },
        {
          id: "14.6",
          text_pre: "They are very kind to me. They treat me",
          text_post: "their own son.",
          opcions: [
            "A like I’m",
            "B as if I’m",
            "C as if I was",
            "D as if I were",
          ],
          solucions: ["C", "D"],
          unitats: [118],
        },
        {
          id: "14.7",
          text_pre:
            "I’m going to be in Moscow next week. I hope the weather will be good",
          text_post: ".",
          opcions: [
            "A while I’ll be there",
            "B while I’m there",
            "C during my visit",
            "D during I’m there",
          ],
          solucions: ["B", "C"],
          unitats: [119],
        },
        {
          id: "14.8",
          text_pre:
            "Joe is away at the moment. I don’t know exactly when he’s coming back, but I’m sure he’ll be back",
          text_post: "Monday.",
          opcions: ["A by", "B until"],
          solucions: ["A"],
          unitats: [120],
        },
      ],
    },

    {
      titol: "Prepositions",
      preguntes: [
        {
          id: "15.1",
          text_pre: "Bye! I’ll see you",
          text_post: ".",
          opcions: [
            "A at Friday morning",
            "B on Friday morning",
            "C in Friday morning",
            "D Friday morning",
          ],
          solucions: ["B", "D"],
          unitats: [121],
        },
        {
          id: "15.2",
          text_pre: "I’m going away",
          text_post: "the end of January.",
          opcions: ["A at", "B on", "C in"],
          solucions: ["A"],
          unitats: [122],
        },
        {
          id: "15.3",
          text_pre: "When we were in Italy, we spent a few days",
          text_post: "Venice.",
          opcions: ["A at", "B to", "C in"],
          solucions: ["C"],
          unitats: [123, 125],
        },
        {
          id: "15.4",
          text_pre: "Our apartment is",
          text_post: "the second floor of the building.",
          opcions: ["A at", "B on", "C in", "D to"],
          solucions: ["B"],
          unitats: [124],
        },
        {
          id: "15.5",
          text_pre: "I saw Steve",
          text_post: "a conference on Saturday.",
          opcions: ["A at", "B on", "C in", "D to"],
          solucions: ["A"],
          unitats: [125],
        },
        {
          id: "15.6",
          text_pre: "What time did you",
          text_post: "the hotel?",
          opcions: [
            "A arrive to",
            "B arrive at",
            "C arrive in",
            "D get to",
            "E get in",
          ],
          solucions: ["B", "D"],
          unitats: [126],
        },
        {
          id: "15.7",
          text_pre: "I’m going",
          text_post: "holiday next week. I’ll be away for two weeks.",
          opcions: ["A at", "B on", "C in", "D for"],
          solucions: ["B"],
          unitats: [127],
        },
        {
          id: "15.8",
          text_pre: "We travelled",
          text_post: "6.45 train, which arrived at 8.30.",
          opcions: ["A in the", "B on the", "C by the", "D by"],
          solucions: ["B"],
          unitats: [128],
        },
        {
          id: "15.9",
          text_pre: "‘Who is this painting",
          text_post: "? Picasso?’ ‘I have no idea.’",
          opcions: ["A of", "B from", "C by"],
          solucions: ["C"],
          unitats: [128],
        },
        {
          id: "15.10",
          text_pre: "The accident was my fault, so I had to pay for the damage",
          text_post: "the other car.",
          opcions: ["A of", "B for", "C to", "D on", "E at"],
          solucions: ["C"],
          unitats: [129],
        },
        {
          id: "15.11",
          text_pre: "I like them very much. They have always been very nice",
          text_post: "me.",
          opcions: ["A of", "B for", "C to", "D with"],
          solucions: ["C"],
          unitats: [130],
        },
        {
          id: "15.12",
          text_pre: "I’m not very good",
          text_post: "repairing things.",
          opcions: ["A at", "B for", "C in", "D about"],
          solucions: ["A"],
          unitats: [131],
        },
        {
          id: "15.13",
          text_pre: "I don’t understand this sentence. Can you",
          text_post: "?",
          opcions: [
            "A explain to me this word",
            "B explain me this word",
            "C explain this word to me",
          ],
          solucions: ["C"],
          unitats: [132],
        },
        {
          id: "15.14",
          text_pre:
            "If you’re worried about the problem, you should do something",
          text_post: "it.",
          opcions: ["A for", "B about", "C against", "D with"],
          solucions: ["B"],
          unitats: [133],
        },
        {
          id: "15.15",
          text_pre: "‘Who is Tom Hart?’ ‘I have no idea. I’ve never heard",
          text_post: "him.’",
          opcions: ["A about", "B from", "C after", "D of"],
          solucions: ["D"],
          unitats: [134],
        },
        {
          id: "15.16",
          text_pre: "I don’t know what time we’ll arrive. It depends",
          text_post: "the traffic.",
          opcions: ["A of", "B for", "C from", "D on"],
          solucions: ["D"],
          unitats: [135],
        },
        {
          id: "15.17",
          text_pre: "I prefer tea",
          text_post: "coffee.",
          opcions: ["A to", "B than", "C against", "D over"],
          solucions: ["A"],
          unitats: [136, 59],
        },
      ],
    },

    {
      titol: "Phrasal verbs",
      preguntes: [
        {
          id: "16.1",
          text_pre: "These shoes are uncomfortable. I’m going to",
          text_post: ".",
          opcions: ["A take off", "B take them off", "C take off them"],
          solucions: ["B"],
          unitats: [137],
        },
        {
          id: "16.2",
          text_pre: "They were playing cards, so I",
          text_post: ".",
          opcions: ["A joined in", "B came in", "C got in", "D broke in"],
          solucions: ["A"],
          unitats: [138],
        },
        {
          id: "16.3",
          text_pre: "Nobody believed Paul at first, but he",
          text_post: "to be right.",
          opcions: [
            "A worked out",
            "B came out",
            "C found out",
            "D turned out",
          ],
          solucions: ["D"],
          unitats: [139],
        },
        {
          id: "16.4",
          text_pre: "We can’t",
          text_post: "making a decision. We have to decide now.",
          opcions: ["A put away", "B put over", "C put off", "D put out"],
          solucions: ["C"],
          unitats: [140],
        },
        {
          id: "16.5",
          text_pre: "‘Have you finished painting the kitchen?’ ‘Nearly. I’ll",
          text_post: "tomorrow.’",
          opcions: ["A finish it up", "B finish it over", "C finish it off"],
          solucions: ["C"],
          unitats: [141],
        },
        {
          id: "16.6",
          text_pre: "You can always rely on Paul. He’ll never",
          text_post: ".",
          opcions: [
            "A put you up",
            "B let you down",
            "C take you over",
            "D see you off",
          ],
          solucions: ["B"],
          unitats: [142],
        },
        {
          id: "16.7",
          text_pre: "Children under 16",
          text_post: "half the population of the city.",
          opcions: ["A make up", "B put up", "C take up", "D bring up"],
          solucions: ["A"],
          unitats: [143],
        },
        {
          id: "16.8",
          text_pre: "I’m surprised to hear that Kate and Paul have",
          text_post: ". They seemed very happy together.",
          opcions: ["A broken up", "B ended up", "C finished up", "D split up"],
          solucions: ["A", "D"],
          unitats: [144],
        },
        {
          id: "16.9",
          text_pre: "I’m going away for a few days. I’ll",
          text_post: "when I get back.",
          opcions: ["A call you up", "B see you off", "C get you back"],
          solucions: ["A"],
          unitats: [145],
        },
      ],
    },
  ],
};
